### ISSUE TITLE
Create a "sandbox project" on AWS

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#102]
# Summary

When we were working on the AWS improvements, we decided that it would be helpful to have our own AWS space to prototype infrastructure and deployments. This would allow us to experiment on our own resources, which would give us more flexibility in what we try out.

# Acceptance criteria

We have a space on AWS, accessible to everyone on the @2i2c-org/tech-team, where we can deploy AWS-related infrastructure.

# Important information

I wonder if @fperez and @consideRatio could provide this space? I believe Fernando mentioned that he is working with some AWS credits for JupyterHub stuff...

# Tasks to complete

- [x] Figure out how to set up a project in AWS that we all have access to
- [x] Decide on who will pay the bill for this infrastructure
    - ~or, find credits for this infrastructure~
- [x] Set up this project/space for our use
- [x] #138
- [ ] Get confirmation that this was set up properly

**Comment by choldgraf** [comment]
Hey all - could somebody help me step through the process of setting up an AWS project? As a start we can use my credit card to power the infrastructure (assuming it won't be super high) but I am not sure how to do this with AWS. Maybe @damianavila or @sgibson91 or @yuvipanda could help me?

**Comment by sgibson91** [comment]
I'd be happy to be an extra set of eyes, but I'm not familiar with AWS myself (yet) :)

**Comment by damianavila** [comment]
@choldgraf I will be happy to help with this... although I think it is just a matter to create a new AWS 2i2c account: https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/

There is no project concept in AWS land as you have in GCP, AFAIK.
You have another level of management with AWS Organizations but that is too far ahead and, actually, I am not sure if you can import other's AWS accounts in an AWS Organization...

Once you have the account ready, you just need to add other 2i2c engineers as full admins: https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_create-admin-group.html

Let me know if you need help in the process.

**Comment by choldgraf** [comment]
OK, I've done the following:

- set up an AWS account called 2i2c-sandbox
- added everyone on the @2i2c-org/tech-team to a group called `tech`
- attached my credit card to this group
- I used your 2i2c usernames as the usernames for this group
- I gave this group admin and IAM access
- Here are [your credentials to access this group](https://docs.google.com/spreadsheets/d/1eIi5SEeAF2T8ycY0_BEMjQIgsRo9rP2xMnf8XMcUXKE/edit?usp=sharing)
    - You'll need to change your password once you log in
    - I'll delete this CSV file in a few weeks

Can you let me know if there's anything else I need to do?

**Comment by consideRatio** [comment]
@choldgraf I've taken part of the password to sign in to AWS on that account - I suggest that we do :+1: on your comment above to signal we've taken part of these credentials.

Note that anyone with their password can sign in and recreate a personal access key and token via https://console.aws.amazon.com/iam/home?region=us-east-2#/users - due to this I've opted at the moment to not save that to disk or similar as I don't plan to use it right now.

**Comment by damianavila** [comment]
@2i2c-org/tech-team, @choldgraf created an issue for follow-up with the AWS access checking at https://github.com/2i2c-org/team-compass/issues/138. I think 👍 here could be confusing to acknoledge access, so let's go with that issue instead 😉 .

**Comment by damianavila** [comment]
I think this is ready to be closed @choldgraf.
