### ISSUE TITLE
Create a once-a-month team meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#109]
# Summary

We now have a few team practices around sharing with one another what we are up to, coordinating work, etc. However, since we're still a remote team, and since most of this coordination is done asynchronously, we rarely see one another face-to-face (well, face-to-screen-to-face 🙃). I would personally enjoy (and wonder if others would as well) having one monthly "all-hands" meeting with everybody on the @2i2c-org/tech-team. This is an issue to discuss and plan for this.

# Meeting information

- Our first team meeting will be at **7:00AM Pacific on Tuesday, July 6th**!
- After this, meetings will be at **8:00AM Pacific on the first Monday of the month**!

# What format would the meeting have?

I'd imagine a meeting format similar to [the JupyterHub Team Meeting](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?view).

We could use a hackmd to structure the meeting itself, and a Zoom room to hold the actual conversation. In the days leading up to the meeting, anybody could add an agenda item that they'd like to discuss. The agenda could be anything - ideally a combination of informal and formal conversation, as desired by the team members. If we had extra time in the agenda, we could just chat for a bit and enjoy one another's company.

The point of the meeting would *not* be to have major decisions, do extensive work that is specific to one project, etc. The main goal is to have some face time and chat with one another, and a secondary goal might be to discuss something interesting or important.

# Who would be there?

Ideally, everybody on the @2i2c-org/tech-team would join this meeting. It wouldn't be strictly required that everybody attend every team meeting, but highly encouraged that you join. Beyond that, anybody on the @2i2c-org/2i2c-team would be invited.

In the future, we might consider if / how to invite people from the outside community into these meetings as well.

# How often and when would this happen?

I'd propose that we shoot for **once a month** at 8:00AM California time. (note: this is pushing it a bit for @yuvipanda, but I'm not sure of any other time where we could get everybody on the team on the call at once)

In the longer term, we might play around with different kinds of formats for this (e.g., alternating time zones, or planning more frequent and informal coffee chats).

# Tasks to complete

- [x] Discuss what people think about a meeting like this. Would it be helpful or fun? Would it be inconvenient or noisy?
- [x] Decide on whether to implement this as a team practice
- [x] Have our first team meeting :-)

**Comment by damianavila** [comment]
I think this is a great idea!
Having the opportunity to join together in some activity, such as the proposed one, will definitely improve the team cohesion and it will be fun! (which is super important for a distributed team like ours).

**Comment by GeorgianaElena** [comment]
I really like the idea too and think it would be beneficial for the team! But, I agree we need to experiment a bit  (from the different timezones perspective) until we make this an established practice.

**Comment by choldgraf** [comment]
Hey all - I've created a few resources that could move us a bit closer to this:

- I created a team calendar here: https://calendar.google.com/calendar/embed?src=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com&ctz=America%2FLos_Angeles
- I've created a sample Agenda for our meeting here: https://hackmd.io/Y5SBMxV7R6CMqzeTXgm5kA
- I've added a PR to the team compass to document this https://github.com/2i2c-org/team-compass/pull/124

**Comment by damianavila** [comment]
Quick feedback: July 5th is the USA Independence Day observed holiday, AFAIK.
I guess some of you (the ones living in the USA) will take that day off, maybe?

**Comment by sgibson91** [comment]
I also have a clash for the first meeting with a Turing way/reproducibility/Binder workshop I'm giving. But otherwise, love this idea!

**Comment by choldgraf** [comment]
Hmmmm - perhaps we could choose a one-off meeting for the first meeting, and then in the future plan on "First Monday of every month"?

I created a when2meet to find a time that overlaps with the most people. How about we fill this out and pick a one-off time for this meeting:

https://www.when2meet.com/?12182180-GcqGJ

Would that work for @2i2c-org/tech-team ?

**Comment by choldgraf** [comment]
ok, I think we have a date for our first meeting:

- **Our first team meeting will be at **7:00AM Pacific on Tuesday, July 6th**!
- **After this, meetings will be at **8:00AM Pacific on the first Monday of the month**!

**Comment by damianavila** [comment]
@choldgraf do you want to add something else here? Otherwise, I think we should close it!

**Comment by choldgraf** [comment]
@damianavila good point! I've got some todo items remaining in https://github.com/2i2c-org/team-compass/issues/144 but we can track them there. Thanks all for having a great first meeting :-)
