### ISSUE TITLE
Define a process for tracking leads

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#132]
# Summary

We currently have two different places to track leads:

- [2i2c-org/leads](https://github.com/2i2c-org/leads/issues) - an old experiment in keeping track of groups we were working with. It isn't up to date, because we were transitioning to using Monday.com which is the platform that ICSI was using.
- the [2i2c Monday.com board](https://icsi-company.monday.com/boards/1140216585) - this was a board to track the same information in a way that more seamlessly worked with the admin team at ICSI, since they are not GitHub natives.
 
Since we are switching to a new fiscal sponsor, we may need to move away from Monday.com anyway. Maybe that means we'll move back to using the `leads` repository, or maybe it'll mean we try to adopt a new platform that is usable by our new fiscal sponsor. We should track that item here.

# Who is this process for?

I think we should keep in mind 3 kinds of people:

- 2i2c team members that are actively generating leads and moving them through the sales process
- 2i2c team engineers that may run infrastructure related to leads
- Administrative team members that need to process paperwork and follow-up on contracts/invoicing (and may be non-technical people in general)

# Acceptance criteria

Given a new potential lead, we should have a clear process / place to create a lead to track their behavior.

Given new information for an existing lead, we should have a clear process of where to track that information and update it.

# Tasks to complete

- [x] https://github.com/2i2c-org/meta/issues/203
- [ ] Discuss with them what kind of admin software they use, and would like us to use
- [ ] Decide on a leads setup we wish to use
- [ ] Document it

**Comment by choldgraf** [comment]
closing this in favor of https://github.com/2i2c-org/team-compass/issues/132

**Comment by choldgraf** [comment]
haha yep, meant https://github.com/2i2c-org/meta/issues/179
