### ISSUE TITLE
Create a SOW for CurveNote

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#134]
# Summary

I need to create a Statement of Work for @rowanc1 / CurveNote at Berkeley, which breaks down the cost of each work item and justifies the total cost.

# Info

<details>
<summary>Here's the "statement of work" guidelines that we need to follow:</summary>

The University Must create our own Statement of Work per the template at the link below. Please note the Statement of Work (SOW) Document is different from the Supplier's Quote. The University department creates our own SOW per the Guideline found in the Template on our Form page (link below); it clarifies the department needs for services to help prevent ambiguity or future disputes from the Supplier. The Supplier provides their proposal/estimate or Quote based upon the elements in the SOW, dated, on supplier letterhead, that identifies the pricing, deliverables, and timeframe for services as defined in the SOW.

</details>

# Tasks

- [x] Discuss with @rowanc1 what deliverables and dates to use.
- [x] Get SOW from @rowanc1 on curvenote letterhead
- [x] #139
- [x] Send to Berkeley admin
- [x] Get response from admin, potentially follow up on new tasks

**Comment by choldgraf** [comment]
Update: started putting together a SOW, but need to get some input from Rowan about the specific deliverables and dates to use. Will get back to this once we have a chance to meet.

**Comment by choldgraf** [comment]
@rowanc1 sent a curvenote SOW, so I'll use this to create one for Berkeley on Monday 👍

**Comment by choldgraf** [comment]
Statement of work for Berkeley / CurveNote created and sent off to the admin for review

**Comment by choldgraf** [comment]
This was approved! so closing issue 👍
