### ISSUE TITLE
Create a bi-weekly deliverables review meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#148]
# Summary

In #144 we discussed creating a **deliverables review meeting**. The goal of this meeting would be to do the following things:

- Go over our major deliverables on the development board
  - Have discussion / refinement around deliverables that need conversation and planning
  - Encourage team members to "pick up" deliverables for development
  - Provide assistance to others that are stuck on some deliverables
  - Discuss which deliverables we should prioritize next
- Go over our major support items
  - Discuss how support has gone for the last 2 weeks
  - Hand off the Support Steward role to the next person
 
# User Stories

- As a team member, this meeting should tell me what are the most important issues to work on next, and which I should focus on myself.
- As the next Support Steward, this meeting should tell me any context information needed for pre-existing support tickets, and where to focus my efforts next.

# Acceptance criteria

We've got this process written up in the Team Compass describing when/how this meeting works.

# Tasks to complete

- [ ] Agree on the general structure and cadence of this meeting
- [ ] Create a calendar event for it
- [ ] Create a meeting notes template to follow
- [ ] Have the first meeting
- [ ] Make edits as necessary
- [ ] Write it all up in the Team Compass

**Comment by choldgraf** [comment]
I've got a draft PR with an agenda for the meeting, in the form of an issues template. I figure that this meeting should primarily be about discussing/refining pre-existing issues, so won't need recurring notes in the way that our monthly team meetings to.

Would love feedback and comments about this structure!

https://github.com/2i2c-org/team-compass/pull/165
