### ISSUE TITLE
Support Steward: @choldgraf

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#180]
# Overview

Old steward: Nobody!
New steward: @choldgraf
Link to steward calendar: <calendar link>

# Support tickets closed in this cycle:

- <List of links>

# Considerations for currently-open issues

...

# Tasks

- [x] Hand-off meeting has happened (relevant notes added to this issue)
- [ ] Perform support steward duties for 2 weeks
- [ ] Hand off to new support steward with new issue
- [ ] Add a task to the "hand off" issue to pin this role in our issues, and also to put it in the "info" column

**Comment by sgibson91** [comment]
What do you think about pinning the "current support steward" issues so they're easily findable?

**Comment by choldgraf** [comment]
@sgibson91 I agree that we should put this in a consistent / findable place. I was actually wondering if we could use the Activity Board for this - since that's kind of a "what's going on right now" board, the left-most column could be an "informational" column with important info in it (e.g. issues for upcoming meetings), and one-such piece of information could be the current Support Steward issue. What do you think?

**Comment by sgibson91** [comment]
I don't see a downside for doing both?

**Comment by choldgraf** [comment]
I think the main downside is potentially having duplicated information rather than a single source of truth, but as long as we make "pin the issue" part of the "Hand off" to-do list, I think it could be fine. I'll add a note to do this in the top comment

**Comment by sgibson91** [comment]
Ohhh, I see - the _board_ is the single source of truth, not the individual issue! Gotcha. I guess I was thinking of this as multiple pathways to the single source of truth (in this case, the issue telling me who the current support steward is) for the sake of visibility

**Comment by choldgraf** [comment]
closing this as @GeorgianaElena is the support steward now 🎉
