### ISSUE TITLE
High-level strategy for the 2i2c Hubs Service pilot

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#192]
# Summary

In the latest team meeting we discussed that it would be helpful to have a high-level overview of the Managed JupyterHub Service that 2i2c is setting up. This would both be helpful for team members to align on our goals and timing, and could act as a pointer for external stakeholders so that they know what we are up to at a high-level.

We should answer questions like:

- What is the scope of the 2i2c pilot?
- What is our vision for the service?
- What are the major areas of work and questions to answer with the pilot?
- What kind of timeline do we expect?

# User Stories

- Team members want to use this information to remain aligned about the "big picture" of the hubs
- External stakeholders would be interested in this information to know what to expect from 2i2c, and how they might fit in with this pilot.

# Tasks to complete

- [x] Write up a draft and get feedback from others: https://github.com/2i2c-org/pilot/pull/85
- [ ] Merge into the Team Compass
- [ ] Come up with 7-8 major enhancements or goals to strive for, and use this to categorize deliverables for this project (perhaps as labels)
- [ ] Create an issue or board to track these major enhancements for the service launch

**Comment by choldgraf** [comment]
Oops - I think this one was prematurely closed, we have a few tasks to complete

**Comment by choldgraf** [comment]
### Update: time to refine our strategy and goals

In our last team meeting we discussed that, as we've onboarded and worked with several communities over the last few months, we're in a better position to understand how many (if any) more we can take on, and where we need to do major work before we're comfortable growing the number of communities we work with.

A few pieces of feedback from that meeting, and we can use this to update this issue and refine the strategy a bit:

**Current situation**

Currently we have ~15 basic hub, ~7 research hubs, ~3 experimental hubs.

**Major questions we should answer for each**

- The amount of usage
- Customization to authenticators
- Image complexity: entirely custom image, repo2docker based image
- Hub adjustments: sidecar, gpu
- Initial development efforts
- Community knowledge: they offload us by avoiding issues in the first place, and being able to understand the complexity of what they need

**How do we decide what feature work is in-scope?**

There are a few communities where we have built features that are not immediately scalable or usable by others. We should avoid doing one-off development work if it is unscalable or takes away from time that would be relevant to more other communities.

What are the criteria we use to decide if something is in scope?

- Ask whether a feature will likely be requested by similar communities in the future. Is it scalable with minimal extra effort? Does it require extra ongoing support needs?
  - For example: BinderHub-style deployments will be requested by many, GPUs requested by fewer, dedicated databases per user dedicated by even fewer. Where do we draw the line?
- Support features that we can reasonably expect our whole team to learn and support
    - "will this feature be something everybody needs to learn about in the end?"
    - We don't want to constrain ourselves to the lowest common denominator of shared knowledge, but also don't want to create information silos.
       
**What is our biggest source of risk?**

If there were one thing you'd focus on to boost our capacity, what would it be?
- Unreliability in automation to deploy, it is a timesink and can also break your focus repeatedly while waiting
- We have made experimental exceptions on what hubs should accomplish
    - Overviewing the experimental adjustments as hubs grow is a challenge
    - While we need to experiment to meet users needs, we need to work to bring back experimentational features to general features or have a practice for managing the experiemental features.
    - Some hubs tends to require more work than others, how do we handle such differences?
- lack of monitoring - makes it hard to know what is going on in the infrastructure

**Proposal for a roll-out strategy**

Here's a proposed phased roll-out strategy for our hubs, to balance iteration and growth with stabilization.

- Phases of growth with fixed number of "slots" for communities in each phase.
- Three major areas that we are working out
  - Infrastructure / tech
  - Process for operations and support
  - Sales and invoicing
- For each area, define questions that we want to answer, or conditions that we want to meet, in order to trigger a new batch of communities that we'll take on.
- Write up a blog post about this plan and share it for feedback, even if we don't intend on taking on any new communities for some time.

**Comment by damianavila** [comment]
> Currently we have ~15 basic hub, ~7 research hubs, ~3 experimental hubs.

Are we certain about these numbers? IIRC, @sgibson91 said we actually have more hubs running (or I heard wrong?).

> Ask whether a feature will likely be requested by similar communities in the future.

I think the key here is "validate" somehow our guesses. If we do not have real validation, we could think something is relevant for the communities but we might be wrong about it. The question is how we validate those features for real?

> Support features that we can reasonably expect our whole team to learn and support

I would go further and say: drop features we already know there is not more than 1 person knowing about the stuff.
And if we really want to go with that feature, then FIRST make another team member learn about it, and then we can re-evaluate.

**Comment by sgibson91** [comment]
> Are we certain about these numbers? IIRC, @sgibson91 said we actually have more hubs running (or I heard wrong?).

42 - but that's if we count staging hubs separately, which we may not want to.
