### ISSUE TITLE
Create a training budget and some recommended training resources

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#204]
# Summary

There may be areas of expertise and learning where professional training could help our team grow their skills more quickly. We should have a process for team training that answers the following questions:

- How much budget do we have to pay for training?
- What kinds of topics are in-scope for covering training?
- Can we recommend specific training workshops or services for team members?
- Is there any training that is _required_ for certain roles?

# Potential topics to consider for training

- Cloud infrastructure and kubernetes
- Team leadership and co-mentorship
- Community management
- Distributed team practices
- Code of Conduct stewardship

# Tasks to complete

- [ ] Answer the questions above
- [ ] Write up a draft of team training policy
- [ ] Converge and merge into the team compass

**Comment by choldgraf** [comment]
Hey all - in the name of transparency and to encourage others to find training opportunities for themselves as well, I wanted to let you all know that I have begun a round of training with a **leadership coach**. I think that's the appropriate training for somebody that is in my role (as opposed to Kubernetes training etc). I plan to use our 2i2c funds to reimburse myself for the training! (it is about $5,000 I believe).
