### ISSUE TITLE
Team training for Kubernetes

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#207]
# Summary

In a few conversations, I've heard from members of the @2i2c-org/tech-team that it would be useful to have access to training in Kubernetes and cloud infrastructure. This could be a good way to normalize skills and knowledge across the team so that we are more effectively able to work together.

What do folks think about finding a Kubernetes training program that the @2i2c-org/tech-team can sign up for and take as a group (or sub-group if some folks are not interested)? This could be something that is "on the clock" and reimbursed by 2i2c.

Here are a few questions we can answer to decide if this is a good path forward:

# Tasks to complete

- [ ] Confirm that team members are interested in this
- [ ] Identify a training / course that focuses on the right topics for what we want to learn
- [ ] Make a plan for how we'll sign up for / take the training...

**Comment by sgibson91** [comment]
I'm definitely interested in covering some k8s fundamentals in depth. A lot of what I know I learned on-the-fly managing mybinder.org, and I wouldn't say my knowledge is particularly well distributed as a result.

**Comment by damianavila** [comment]
+1 on what @sgibson91 said. Definitely interested.

**Comment by sgibson91** [comment]
Other topics I'd like some training on 😁 :

- Networking
- NFS

**Comment by choldgraf** [comment]
we discussed this one in the @2i2c-org/steering-council meeting a bit today as well. I wanted to add some extra thoughts to see if it resonated with others:

One of the things that we discussed was the challenge around finding generic cloud training opportunities that cover the topics that are specifically relevant to 2i2c. Given that the nature of our DevOps is relatively repeatable and focused on the JupyterHub/data science context, someone brought up the idea of developing **training materials that are focused on 2i2c Hub Engineers**. I think we imagined something like the following:

1. An "Introductory guide to being a 2i2c Engineer". This guide would be focused on teaching people the fundamentals of the major tools, workflows, and infrastructure setups that go into deploying and operating a JupyterHub. The high level sections would be the major areas that are *most important* for somebody to know about.
2. A set of slides and hands-on exercises that are meant to be followed in a workshop style. These slides would pull content from the documentation, and meant to be followed in a "live tutorial" style. This might be similar to workshops that we've run for BinderHub or JupyterHub deployments.

A part of these resources could also be pointers to external training around specific topics in cloud infrastructure (perhaps some of it paid, which 2i2c could definitely cover the cost of).

Two other considerations that I think are worth mentioning:

- I wonder if materials like this could be useful for the broader JupyterHub community as well, and perhaps this might be relevant to the Community Strategy that @sgibson91 is spearheading soon? (e.g., training materials to help newcomers get up-to-speed with the JupyterHub stack)
- Materials like this might also be useful as a *service* for institutions that want 2i2c to help train their IT people, engineers, etc in how to deploy JupyterHub in the cloud.

Curious if folks think that this would be a useful resource for our team or if you have other thoughts! It would definitely be a more long-term project and investment in the team, but could potentially be a way to more easily onboard and upskill new team members.

**Comment by sgibson91** [comment]
I like this idea for sure. I'm concerned about who would create 2i2c-specific materials though. For example, I don't know what I don't know yet :) And I worry that we will perpetuate the same gaps in knowledge if we self-generate. It might just be that I need the confidence that I "know enough" to contribute to such materials though.

**Comment by damianavila** [comment]
> I like this idea for sure. I'm concerned about who would create 2i2c-specific materials though. For example, I don't know what I don't know yet :) And I worry that we will perpetuate the same gaps in knowledge if we self-generate.

:100: I was going to write the same :wink:
I think the idea is great but, at the same time, I think this is another discussion, not the one we started at the top.
Let's solve our training first, then prepare training for others, I would say...

**Comment by choldgraf** [comment]
I agree with all of this - though I think that we can make progress on both with the same action.

One reason I brought up this idea was because, in researching "cloud training" courses, bootcamps, etc, I am not sure exactly what we need to learn. It's hard for me to choose because I am the least knowledgeable about cloud skills in general. So it might be helpful for us to first describe the major topics that will likely benefit the team for training. Then it will be easier to find courses, trainings, etc that feed into those topics. They might then also be a starter for top-level categories in a 2i2c training manual in the future.

**Comment by consideRatio** [comment]
Conceptual overview of k8s, common patterns in k8s, basics of having deployed a helm chart and debugged some error doing it or similar. That seems like a minimal curriculum with good coverage of things to provide a good ground to learn more etc.

I have not thought this through that much, but to me, the most important insights was gained from watching a video about how k8s work ( called kubernetes deconstructed, by a person named carlson, part of domio, or similar ).

I can link to that later from a non-mobile device.

I think armed with basic experince, conceptual overview, and some known common patterns in k8s - one can catch onto the rest a lot easier.

**Comment by damianavila** [comment]
I guess something related to differences in k8s offering from the main cloud providers could be useful as well, maybe?

**Comment by sgibson91** [comment]
I'd be interested in an intro to Dask as well actually, as I've never used it.

**Comment by yuvipanda** [comment]
https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/ maybe? It also counts as professional development, for use in future jobs!

**Comment by choldgraf** [comment]
### Update: let's try the Kubernetes administrator trainings

Given that there are a million Kubernetes trainings out there, let's just "pick one" and see how it goes. Given that CNCF is the de-facto steward of the Kubernetes ecosystem, that seems like a good place to start.

So, I propose that we adopt the following policy:

### Proposed policy for team training and certifications

2i2c encourages all team members to seek out professional training in skillsets that are relevant to their job title.
To support these efforts, we follow these guidelines:

- Team members that go through external training programs are welcome to do so "on the clock"
- In general, 2i2c can use central funds to pay for any costs associated with training and personal development.
  - The easiest way to do this is through reimbursement
  - If that is not preferable we can probably pay for trainings with the 2i2c Expensify credit card.
- We'll choose some **recommended trainings** that any team member can safely take on organization time + get reimbursed.
- For other trainings we haven't vetted, please check with Chris first.
  - In the future, we should explore a policy like "each team member has an annual personal training budget of around $2,000" or something. I'll ask around at CS&S what they do.

### Recommended trainings for Kubernetes

The following trainings are recommended for any 2i2c engineer:

- [Kubernetes Fundamentals](https://www.cncf.io/certification/training) (self-paced, $300)
- [Kubernetes for Developers](https://www.cncf.io/certification/training) (self-paced, $300)
- [Certified Kubernetes Administrator exam](https://www.cncf.io/certification/CKA/) (online exam, $375)

### Next steps

- [ ] Does this proposal seem reasonable to others? Any suggestions?
- [ ] Would any team members like to volunteer to take one of the trainings listed above?
- [ ] Write this up in the team compass

**Comment by GeorgianaElena** [comment]
This sounds super reasonable to me and I believe it's a great starting point!

Few ideas for the future and suggestions

* > 2i2c encourages all team members to seek out professional training in skillsets that are relevant to their job title.

   I believe we should also think about this from a new hire perspective in the future. Maybe we can find a training program or *create* our own list of on-boarding "readings" to help navigate a new hire in the first few months?

* > In the future, we should explore a policy like "each team member has an annual personal training budget of around $2,000" or something. I'll ask around at CS&S what they do.

  I agree that this may be the way to go. I believe a training budget makes more sense because it's based on self-evaluation, rather that needing to create/recommend per-person tailored trainings and it gives the freedom to pursue a preferred existing or new skill-set.

* > Team members that go through external training programs are welcome to do so "on the clock"

  Let's use "on the job" here, rather than "on the clock", since I *believe* it's more close to 2i2c?
  
> Would any team members like to volunteer to take one of the trainings listed above?

Yes, please! :rocket: :D

**Comment by choldgraf** [comment]
@GeorgianaElena do you want to volunteer to be out first kubernetes training guinea pig? :-)

And agreed that "on the clock" is probably not the best wording haha
