### ISSUE TITLE
Documentation for potential communities of the Managed Hubs Service

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#211]
# Summary

We need documentation that is designed for decision-makers within an organization to learn about the Managed JupyterHub Service, and decide if they'd like to use it. We should decide on a strategy and location for this information, and get it up to a workable state worthy of a "beta" release.

# Benefit

This is important because potential community representatives may not know (or care) much about how to do things on the hubs, and so we should have high-level documentation that is tailored for people learning more from the beginning. The goal should be to help them understand if a Managed JupyterHub is the right use-case for them.

# Tasks to complete

- [ ] Brainstorm the major questions that a person would want to know as they look into the Managed JupyterHubs Service
- [ ] Decide on a location where this information will live
- [ ] ...address issues as-needed to bring the documentation up to speed
- [ ] Decide that our documentation is in a good-enough state to consider "beta state"

# Important information

Two places where this kind of information currently exists:

- [Our pilot documentation](https://pilot.2i2c.org) (which may be re-branded the "Hub Administrator guide")
- Our [2i2c website](https://2i2c.org/infrastructure/)
