### ISSUE TITLE
Try 60 minute meetings for sprint planning

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#214]
# Summary

The last couple of sprint planning meetings have felt a bit rushed to me. I think that it is important to make time for discussion and input from the team, and I worry that by rushing the sprint planning in 30 minutes, we are discouraging team members from participating.

I propose that we make the sprint planning meeting **60 minutes instead of 30 minutes** (by extending it an extra 30 minutes on Tuesdays).

In addition, having a standing 60 minute meeting is a lot, so I suggest that we plan to do this for **2 months, and then revert to fortnightly sprints**. Then we'd have one 60 minute meeting every 2 weeks to plan our sprints, which seems reasonable.

# Tasks

- [x] Propose this change in the team compass
- [x] Team decides if they consent to this
- [ ] Merge and begin practicing

**Comment by damianavila** [comment]
I had the same "rush" impression... maybe because we are just starting...
Most likely, 60 min is totally OK for a fortnightly sprint meeting, so I am OK about having that in the temporary weekly sprint.

I concur with your proposal, @choldgraf.

**Comment by yuvipanda** [comment]
If we set an explicit end date for the weekly sprints, +1 on this

**Comment by choldgraf** [comment]
OK sounds good - I've updated https://github.com/2i2c-org/team-compass/issues/182 to include a check-in on October 1st to decide if we want to move to fortnightly. I've also updated the calendar so that this meeting is now 1 hour! Will make a quick Team Compass PR so this is reflected in our docs
