### ISSUE TITLE
Re-purpose our `prio` labels to be `impact` instead

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#227]
### Description

I propose that we remove the `prio:` GitHub labels and instead replace them with labels based on **impact** (so, `impact: low / med / high`).

We currently use a few GitHub labels to encode "priority": `prio:low / med / high`. I have found that these labels are under-specified. Priority is very context- and person-dependent, and also changes fairly frequently (e.g. what is low-priority yesterday may be high-priority tomorrow). Moreover, we currently have two different ways to encode priority: one is with the label, and the other is via an issue's placement in our development backlog / ordering on a column.

Instead I think we should use "impact" and define the meaning of this label specific to an issue's functional area. For example:

- the impact of an infrastructure feature might be defined by the number of users that would benefit from it (all users == high, ~half users == med, ~quarter users == low) OR particularly important users could trigger "high" as well.
- the impact of a bug might be defined by whether functionality is critically impaired or just cosmetic, or whether it is complex to reproduce or is reproduced by everyone
- the impact of an administrative task might be defined by whether it is required to get some essential work done, or just general housekeeping

There would still be a degree of subjectivity and judgment there, but I think this is still more concrete than "priority". In addition, the person that applies an "impact" label should ensure that the value/benefit is described in the issue well enough to justify the label.

### Value / benefit

If we instead used "impact" labels, I believe that it would be easier to have a concrete definition for each issue that would be more stable over time. Moreover, impact maps relatively nicely onto our "value/benefit/user story" practice in describing our team issues. Impact would be an important deciding factor in prioritization (in general, we want to work on things that are high-impact!) but it wouldn't **define** the priority, it would just be an important factor for it.

### Implementation details

I propose that we try this out on the `pilot-hubs/` repository for a month and see if it improves the signal-to-noise of the issues, or helps us triage and prioritize more easily.

If nobody objects, I'll plan to remove all `prio:` labels from pilot-hubs, and replace them with "impact" labels (and potentially re-assign labels to issues as needed).

### How to define "impact"?

Here is the definition we can use for impact across various kinds of categories:

- **Features / Enhancements**
  - `impact: high`: Will be seen and commonly used by nearly all users OR has been requested by an abnormally large number of users OR is of particular importance to a really important user
  - `impact: med`: Will be useful to many users but not an overwhelming amount. Most issues should be in this category.
  - `impact: low`: Is useful but not a critical part of workflows OR is a niche use-case that only a few users may need.
- **Bugs**
  - `impact: high`: Is disruptive to nearly all users, or critically disruptive to many users (e.g., sessions won't work at all)
  - `impact: med`: Is disruptive to our users, but not in a critical way. Most issues should be in this category.
  - `impact: low`: Is cosmetic or minimally disruptive, or only affects a small number of users.
- **Team process or admin**
  - `impact: high`: Is a crucial component of our team process that will have across-the-board improvements in our practices
  - `impact: med`: Is important but not a critical part of our workflow.
  - `impact: low`: Needs to be done but is not going to critically affect our team practices any time soon.

### Tasks to complete

- [x] Nobody objects to trying this workflow in pilot-hubs/
- [x] Swap out `prio:` labels for `impact:` labels in `pilot-hubs/`
- [ ] Revisit this practice in October and decide if we should continue it
- [ ] Decide whether to apply it to other repositories
- [ ] Write up in the team compass

**Comment by sgibson91** [comment]
I've seen an `impact: 3` label somewhere (sorry I can't be more specific as I'm wading through my deluge of GitHub emails :D ). What happened there? If we're using numbers, what's the scale and direction? (Is 1 higher impact than 5, or reverse, e.g.?)

**Comment by choldgraf** [comment]
ah yes - this week I was trying using numbers instead of words in the hopes that this would reduce a bit of visual clutter on the boards (and also cause them to be sorted more properly). In that case 1=low, 2=med, 3=high

If folks think that numbers introduce confusion because of the ambiguity you describe, I am happy either way - this was just an experiment

**Comment by sgibson91** [comment]
I think a numerical scale is not as helpful without also a description of the scale, and that's means finding where that description is documented. Whereas `impact: low` is much more easily parsable at a glance and has a much improved probability of being correctly understood in comparison with an `impact: high` label.

**Comment by choldgraf** [comment]
👍 - I'll wait and see if others have opinions too (@damianavila ?), but happy to change back to letters if nobody objects

**Comment by GeorgianaElena** [comment]
> I've seen an impact: 3 label somewhere (sorry I can't be more specific as I'm wading through my deluge of GitHub emails :D ). What happened there? If we're using numbers, what's the scale and direction? (Is 1 higher impact than 5, or reverse, e.g.?)

I actually wanted to ask about this too.

For me the confusion was more about *"How many levels of impact are there?"*. Somehow the color of the `impact` label made sense in my head and I got the direction right :sweat_smile: (I wasn't sure I was right until now, tho)

I guess what I'm trying to say, is that I think letters make more sense and are less confusing :+1:

**Comment by damianavila** [comment]
> 👍 - I'll wait and see if others have opinions too (@damianavila ?), but happy to change back to letters if nobody objects

Yep, let's go with letters :wink:

**Comment by choldgraf** [comment]
thanks @GeorgianaElena + @sgibson91 for that helpful perspective. OK I will switch them back now :-)

More generally, do people like the idea of "impact" over "priority" for labeling?

**Comment by choldgraf** [comment]
OK I'm gonna close this one as I haven't seen any objections - I'll migrate `prio` to `impact` across repositories as the opportunity comes up!

**Comment by choldgraf** [comment]
oops just realized we need to update the team compass, reopening and will open a quick PR
