### ISSUE TITLE
Blog post: 2i2c quarterly update Q3

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#235]
### Description

At the end of last May, we wrote up [a short overview of what 2i2c has been up to](http://2i2c.org/posts/2021/six-month-update/). We should extend this practice to cover the next few months of development. Moreover, I think that a nice cadence for these meta updates would be **quarterly**, so I'll scope this post to **Q3 2021** (July, August, and September and we can include June in there this time as well).

I'll try to collect major updates and themes from 2i2c over the last few months, and give an idea of where I think we are headed next. This may also be a good opportunity for us to bake this in to our regular strategic planning.

### Value / benefit

Providing organization-wide heartbeats is an important way to provide transparency to others about what we have been up to, and where we are going. It's a way to show some dyanamism for people who are not paying close attention to our repositories, and is also a signal-boost that others can follow.

### Implementation details

I think we should just collect links and references in this issue, and then in October 2021 write up a summary blog post that compiles them together.

### Tasks to complete

- [x] Until October 1st 2021, collect major updates from 2i2c here. Paste or cross-link below.
- [x] Write up a blog post draft (see link below)
- [x] Feedback on draft
- [x] Post on Thursday October 14th unless there are objections

### Updates

- **2021-10-11**

  I've put together a draft for a "Community update". It includes a few major highlights, challenges, and next 
  steps for what we've been up to. I'd love any comments or edits!

  https://hackmd.io/uQGx-x6sReG5JbuR7pqHuw

  If there are no major objections, I hope to post this on our blog on **Thursday**.

**Comment by choldgraf** [comment]
As a first step to keeping track of our updates, I added some quarterly tags for the team compass repository. This makes it easy to compare what has changed in team-compass between major chunks of time quite easily.

For example, here's the changes to this repo since Q2 ended:

https://github.com/2i2c-org/team-compass/compare/2021.06.01...main

And here's the changes we made during Q2 2021:

https://github.com/2i2c-org/team-compass/compare/2021.04.01...2021.07.01

this might be a nice way for us to track our infrastructure changes as well...since we don't follow any kind of "versioning" convention, doing so by quarter (or month) seems like a reasonable approach? Let's see how it works here first though :-)

**Comment by choldgraf** [comment]
Another thought here is that we could use `github-activity`. So for example one could do:

`github-activity -s 2021-07-01` and the result today would be:

# master@{2021-07-01}...master@{2021-09-04}

([full changelog](https://github.com/2i2c-org/team-compass/compare/679634d21365c357c397937e1ef366e20ffe3897...7c97ddd9a2fcae6acc86e3bc88939f551d92f3e0))

## Merged PRs

- Remove extra chartpress in action [#234](https://github.com/2i2c-org/team-compass/pull/234) ([@choldgraf](https://github.com/choldgraf))
- Checking links and fixing broken links [#233](https://github.com/2i2c-org/team-compass/pull/233) ([@choldgraf](https://github.com/choldgraf))
- Add general issue template [#225](https://github.com/2i2c-org/team-compass/pull/225) ([@choldgraf](https://github.com/choldgraf))
- Add upstream repo note [#223](https://github.com/2i2c-org/team-compass/pull/223) ([@choldgraf](https://github.com/choldgraf))
- Simplify weekly issues creation [#221](https://github.com/2i2c-org/team-compass/pull/221) ([@choldgraf](https://github.com/choldgraf))
- Add merge and review policy [#220](https://github.com/2i2c-org/team-compass/pull/220) ([@choldgraf](https://github.com/choldgraf))
- Update ICSI -> CS&S [#219](https://github.com/2i2c-org/team-compass/pull/219) ([@choldgraf](https://github.com/choldgraf))
- Mention external repository [#218](https://github.com/2i2c-org/team-compass/pull/218) ([@choldgraf](https://github.com/choldgraf))
- Update weekly meeting status to 60m [#217](https://github.com/2i2c-org/team-compass/pull/217) ([@choldgraf](https://github.com/choldgraf))
- Add section on sops and secrets [#215](https://github.com/2i2c-org/team-compass/pull/215) ([@choldgraf](https://github.com/choldgraf))
- Fix sync issue timings [#209](https://github.com/2i2c-org/team-compass/pull/209) ([@choldgraf](https://github.com/choldgraf))
- Adding language about support steward [#202](https://github.com/2i2c-org/team-compass/pull/202) ([@choldgraf](https://github.com/choldgraf))
- Update meeting time to be correct [#194](https://github.com/2i2c-org/team-compass/pull/194) ([@choldgraf](https://github.com/choldgraf))
- Adding notes for August team meeting [#193](https://github.com/2i2c-org/team-compass/pull/193) ([@choldgraf](https://github.com/choldgraf))
- Fix close action [#189](https://github.com/2i2c-org/team-compass/pull/189) ([@choldgraf](https://github.com/choldgraf))
- Update team meetings and deliverables workflow [#188](https://github.com/2i2c-org/team-compass/pull/188) ([@choldgraf](https://github.com/choldgraf))
- Update the roles section to be more complete [#178](https://github.com/2i2c-org/team-compass/pull/178) ([@choldgraf](https://github.com/choldgraf))
- Make Slack communication section up to date [#177](https://github.com/2i2c-org/team-compass/pull/177) ([@choldgraf](https://github.com/choldgraf))
- Adding roles to Managed JupyterHub Service [#168](https://github.com/2i2c-org/team-compass/pull/168) ([@choldgraf](https://github.com/choldgraf))
- Deliverables meeting template [#165](https://github.com/2i2c-org/team-compass/pull/165) ([@choldgraf](https://github.com/choldgraf))
- Refactoring documentation and adding meeting practices [#164](https://github.com/2i2c-org/team-compass/pull/164) ([@choldgraf](https://github.com/choldgraf))
- Label in gh issue template [#162](https://github.com/2i2c-org/team-compass/pull/162) ([@choldgraf](https://github.com/choldgraf))
- Template update [#161](https://github.com/2i2c-org/team-compass/pull/161) ([@choldgraf](https://github.com/choldgraf))
- Team meeting template [#160](https://github.com/2i2c-org/team-compass/pull/160) ([@choldgraf](https://github.com/choldgraf))
- Update team sync template [#154](https://github.com/2i2c-org/team-compass/pull/154) ([@choldgraf](https://github.com/choldgraf))
- Add july meeting [#149](https://github.com/2i2c-org/team-compass/pull/149) ([@choldgraf](https://github.com/choldgraf))
- Document providing GCP & AWS access [#145](https://github.com/2i2c-org/team-compass/pull/145) ([@yuvipanda](https://github.com/yuvipanda))

## Contributors to this release

([GitHub contributors page for this release](https://github.com/2i2c-org/team-compass/graphs/contributors?from=2021-07-01&to=2021-09-04&type=c))

[@choldgraf](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3Acholdgraf+updated%3A2021-07-01..2021-09-04&type=Issues) | [@consideRatio](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3AconsideRatio+updated%3A2021-07-01..2021-09-04&type=Issues) | [@damianavila](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3Adamianavila+updated%3A2021-07-01..2021-09-04&type=Issues) | [@GeorgianaElena](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3AGeorgianaElena+updated%3A2021-07-01..2021-09-04&type=Issues) | [@sean-morris](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3Asean-morris+updated%3A2021-07-01..2021-09-04&type=Issues) | [@sgibson91](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3Asgibson91+updated%3A2021-07-01..2021-09-04&type=Issues) | [@yuvipanda](https://github.com/search?q=repo%3A2i2c-org%2Fteam-compass+involves%3Ayuvipanda+updated%3A2021-07-01..2021-09-04&type=Issues)

**Comment by damianavila** [comment]
> Contributors to this release

The last one (I think it is automatically generated?) is building failed URLs (taking my handle as one example but it fails with all the handles):

https://github.com/search?q=repo%3A2i2c-org%2FNone+involves%3Adamianavila+updated%3A2021-07-01..2021-09-04&type=Issues

It should be (pointing to the org instead of the repo): 
https://github.com/search?q=org%3A2i2c-org+involves%3Adamianavila+updated%3A2021-07-01..2021-09-04&type=Issues

Btw, quick question, how do we capture stuff not represented on GitHub?

**Comment by choldgraf** [comment]
I'm starting to work on a blog post about this here:

https://hackmd.io/uQGx-x6sReG5JbuR7pqHuw

I need to keep iterating on it a bit to figure out how to prevent it from being super long and complex. It is roughly broken up into these 4 main sections, corresponding to 4 ways that 2i2c wishes to have impact on our communities:

1. Organizational updates
2. Hub service updates
3. Projects / collaborations updates
4. Open source upstreams / support

I'm not sure that the draft is ready for 👀 yet but if others are curious to check it out, you're more than welcome!

**Comment by damianavila** [comment]
As I said in the meeting, in general, I really like it!
I will add specific comments on the linked PR.
