### ISSUE TITLE
Move monthly team meetings from Monday to Wednesday

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#237]
### Description

We should move our team meetings off of either Mondays or Fridays, and onto Tue/Wed/Thu. We should pick one of these days for our monthly team meetings.

### Value / benefit

By avoiding Mon/Fri, we'll be less likely to lose people because of holidays or vacation, and we'll all more easily be able to have flexible weekend working schedules :-)

### Implementation details

We should plan around some other important meetings as well:

Other meetings to consider:

- Weekly sprint planning meeting: Tuesdays
- Monthly steering council meetings: Tuesdays
- Jupyter Community meeting: Tuesdays
- Turing Way Collaboration Cafes: Wednesdays
- Berkeley tech strategy meeting: Thursdays

Another thing to consider is how this meeting fits in with our weekly "sprint planning" meeting. It feels natural to me that the monthly meeting comes towards the end of a sprint, rather than at the beginning of a new one. This more naturally creates space for reflection and discussion rather than thinking about tactical issues. We should decide if we want to follow the same pattern in moving the meeting time.

### Tasks to complete

- [x] Arrive at a time for meeting planning to work 
- [x] Update Google Calendars for future meeting changes
- [ ] Prep a PR to update our team meeting practices
- [ ] On **Wednesday the 29th** begin new process for team meetings

### Decision

We'll follow the plan in this comment: https://github.com/2i2c-org/team-compass/issues/237#issuecomment-914666552

**Comment by choldgraf** [comment]
How do folks feel about this proposal:

- Move Sprint planning to Wednesdays (so Sprints are now Wed -> Wed) off-cycle with Turing Collaboration cafes (is it possible for us to move it in _time_ so that this works @sgibson91 ?)
- Move monthly team meetings to Tuesdays (off-cycle with the Jupyter community meetings and the Steering Council meeting)

**Comment by sgibson91** [comment]
> * Move Sprint planning to Wednesdays (so Sprints are now Wed -> Wed) off-cycle with Turing Collaboration cafes (is it possible for us to move it in _time_ so that this works @sgibson91 ?)

Collab Cafés run 15:00-17:00 Europe/London time on the first and third Wednesdays of the month

HackMD: https://hackmd.io/@turingway/collaboration-cafe
Calendar of all Turing Way events: https://calendar.google.com/calendar?cid=dGhldHVyaW5nd2F5QGdtYWlsLmNvbQ

**Comment by damianavila** [comment]
> Move Sprint planning to Wednesdays (so Sprints are now Wed -> Wed) off-cycle with Turing Collaboration cafes 

:+1: to the idea of having it on Wed.

> Collab Cafés run 15:00-17:00 Europe/London time on the first and third Wednesdays of the month

What about every Wed 17-18 London time? @yuvipanda, is that too late for you? Other's thoughts?

>Move monthly team meetings to Tuesdays (off-cycle with the Jupyter community meetings and the Steering Council meeting)

:+1: as well

**Comment by sgibson91** [comment]
> What about every Wed 17-18 London time?

Once we move to fortnightly sprints (which I think is happening at the end of the month?), we can keep the current time slot so long as we stick to the 2nd and 4th weeks of the month as we'll be off-cycle with the Turing Way.

**Comment by choldgraf** [comment]
# A proposal:

How about this then:

**Starting Wed, September 29th**:

- **Sprint Planning**
  - On Wednesdays at 7:30am California time /  15:30 London / 16:30 CET / 8pm India.
  - Every 2 weeks. If we start on the last week of September, that should put us off-cycle with the Turing meetings.
- **Team Meetings**
  - On Tuesdays at 7:30AM California time
  - Every month. Should happen on the same week that a sprint cycle is ending, the next would be on **October 12th**.

I think that would put us off-cycle with Jupyter community calls and Turing collaboration cafes

**Comment by yuvipanda** [comment]
Sounds good to me!

**Comment by choldgraf** [comment]
OK I think that we have a time that works! I've updated the top comment to reflect our latest plan. For this sprint I'll make a PR that updates our team meeting practices, but can leave it as a draft until the week of the 29th when we can begin these new practices ✨

**Comment by consideRatio** [comment]
Sounds good to me!
