### ISSUE TITLE
Create a price quote template

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#242]
### Description

We'll need a template for quoting a price and advertising major functionality of the Managed JupyterHub Service. The template should cover these major things:

- Executive Summary of the service
- Community-specific information like start date etc
- The specific service they're getting (e.g., Pangeo, base hub, etc) as well as the period of performance and expected billing cycle.
- Full-cost price for the service
- Discount amount + discounted price for the service
- The proper branding for 2i2c/CS&S.

### Value / benefit

This will allow us to repeatably provide quotes to stakeholders in organizations so that they can advocate for purchasing services from 2i2c internally. It will also reduce redundant actions during the sales process.

### Implementation details

The easiest thing to do is probably to create a Google Doc that we can copy and modify for specific communities. We can then store that document in a community-specific folder for archiving.

There's an initial draft of the template here: https://docs.google.com/document/d/1OptrdpH0CAHhHwJc9PaMc10Rpcenw638zBjVtRRaTHs/edit#

A longer-term option could be to explore using a form generation service via AirTable or a similar tool.

### Tasks to complete

- [ ] Create an initial draft of the template
- [ ] Iteration and improvement
- [ ] Prototype with a few communities and improve as needed

**Comment by choldgraf** [comment]
This is now completed (and somewhat superceded by #262)
