### ISSUE TITLE
Roadmap planning meeting Q4: Hub Service alpha launch

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#249]
### Description

As a part of #229 I think that we should start practicing a (roughly) quarterly roadmapping meeting. The goal of this meeting is to zoom out a bit, think about our major objectives, and define some initiatives (AKA, collections of issues) that help us accomplish those objectives. The result wouldn't be set in stone, but it align us all on the major things we need to do towards the "big picture".

I think that right now, we have two major strategic objectives:

- Deploy an alpha-level Managed Hubs Service
- Deploy the Pangeo cluster and migrate the Pangeo community onto our Pangeo hub

I propose that we have a **1.5 hour meeting** to do the following things:

- Agree on the major things that need to happen (both technical and non-technical) to meet these two objectives.
- Focus most of the conversation on the Managed Hubs Service (assuming that the Pangeo infrastructure is a bit more straightforward in terms of next steps)
- Make sure that each of these things is encoded in an issue and collected somewhere that we can track.

The result of this could be a "roadmap" for how we get to the launch of the managed hubs service.

### Meeting time

The meeting will be on October 6th. Here's a link: https://calendar.google.com/event?action=TEMPLATE&tmeid=NTEyb2Rqb2ZycW5wcHMxMGdjYnV1ZDhlcm8gY180aGpqb3VvamQ4cHNxbDlpMWE4bmQxdWZmNEBn&tmsrc=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com

### Scoping this meeting

This would be a **planning and scoping meeting** - not a high level vision meeting. We don't want to talk about the future of academic publishing, we want to plan out the next 3 months of work. So it will be more "tactical" than "strategic", though we will talk through some strategy stuff at the beginning most likely.

### Who should join

I think this will be most-effective if we include many perspectives in this conversation. We should involve many stakeholders in this if possible. Not only the @2i2c-org/tech-team but potentially members of the @2i2c-org/steering-council as well (I know that @colliand is eager to participate in these conversations). 

### Fill in your availability!

I propose that we have this meeting sometime in the first week of October (before @yuvipanda goes on vacation).

If you'd like to attend, please fill in your availability here:

- https://www.when2meet.com/?12988552-iuV2t

All are welcome to join - if you wish, please fill out your availability and we can find a time. I think that at least one person from the @2i2c-org/tech-team (maybe @yuvipanda) and one person that has more of a sales perspective (maybe @colliand) should attend, so I'll use that as a constraint on scheduling.

### Tasks

- [x] Fill in the when2meet: https://www.when2meet.com/?12988552-iuV2t
- [x] After 3 days, we'll pick a time.
- [x] Have the meeting and figure out next steps

**Comment by yuvipanda** [comment]
I'm excited to be part of this! I've filled in my availability :)

**Comment by colliand** [comment]
I look forward to this meeting! Thanks for bringing us together @choldgraf.

**Comment by choldgraf** [comment]
### 2021-09-07

Looking at the responses, let's meet on **October 7th**. I've created a team calendar link and invited the @2i2c-org/tech-team and the @2i2c-org/steering-council . Here's a link to the meeting: https://calendar.google.com/event?action=TEMPLATE&tmeid=NTEyb2Rqb2ZycW5wcHMxMGdjYnV1ZDhlcm8gY180aGpqb3VvamQ4cHNxbDlpMWE4bmQxdWZmNEBn&tmsrc=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com

I'll post some prompts beforehand as well so that we can prime some thinking!

**Comment by choldgraf** [comment]
### 2021-09-29

I've heard from @yuvipanda that he had a meeting placed on his calendar at Berkeley on the previous time, so this meeting is moved one day earlier to **October 6th**. I've updated the calendar entry as well!

**Comment by choldgraf** [comment]
closing this one as we had this meeting back in early October! We can iterate on the planning process in subsequent iterations!
