### ISSUE TITLE
Tech Team Update: 2021-01-27

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#27]
Hey @2i2c-org/tech-team - we're a couple of days late for our latest updates. Sorry about that! Can folks fill out the [HackMD](https://hackmd.io/i2Siurp1TkmPYgn3ZgxFQw) with their own updates? ✨ 

- **Updates HackMD**: https://hackmd.io/i2Siurp1TkmPYgn3ZgxFQw
- **Team Sync history**: https://2i2c.org/team-compass/team/tech/sync/

# ToDo

- [x] Clean up the [HackMD](https://hackmd.io/i2Siurp1TkmPYgn3ZgxFQw) for this update
- [x] Ping the team members in [`#tech-updates`](https://2i2c.slack.com/archives/C01GLCC1VCN)
- [x] Wait 2-3 days
- [x] Copy/paste into the `team-compass` repository
- [x] Clean up the HackMD
- [x] Link to new updates in `team-compass/` in [`#tech-updates`](https://2i2c.slack.com/archives/C01GLCC1VCN)

**Comment by consideRatio** [comment]
Done, I think this is a great system btw @choldgraf!

I like:
- Topics to fill in with some suggestive examples
- The first topic is about being thankful :heart:

**Comment by choldgraf** [comment]
Thanks all for filling this in!
