### ISSUE TITLE
Team walkthrough of Pangeo's Dask workflows

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#273]
### Description

@rabernat very kindly to offered to arrange a meeting with me to walkthrough some dask workflows to help my mental model of the project. @choldgraf would also be interested in this, I suspect a few other members of the team too!

### Value / benefit

- As the engineers maintaining this infrastructure, it's good to understand _how_ it's being used even if we're not using it ourselves in our day-to-day

### Tasks to complete

- [x] @rabernat, @choldgraf, @sgibson91 and anyone else who is interested in attending to fill out the below when2meet to find the best time for this run-through
	- https://www.when2meet.com/?13371325-uLkcY
- [x] When date/time is confirmed, @sgibson91 will send out an invite
- [x] Have the meeting!
