### ISSUE TITLE
Decide where to keep track of development efforts

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#28]
# Background

While we may have hub configurations and deployments split across many repositories, we will likely have many development opportunities that are broadly applicable across these repositories. One example is [hub costs](https://github.com/2i2c-org/pangeo-hubs/issues/27) that was surfaced in the pangeo hubs repo, but is likely useful to anybody.

We should have these development tasks organized such that anybody on the 2i2c team (and ideally outside the 2i2c team) can quickly answer

- what are the general development ideas 2i2c is working on?
- where can I observe this development and pitch in?
- what needs to be done to accomplish these goals?

# Question

What process should we adopt that allows for this to happen? It seems clear that we need some kind of central "clearing house" for these development priorities. A few ideas for what this could be:

- A single `development` repository where we keep track of issues for development and where it is happening (similar to our `leads/` repository).
- A single organization-wide GitHub Project board that contains development-focused issues that are spread out across many repositories

# ToDo

- [ ] Agree on a process for organizing new development and upgrades
- [ ] Implement whatever needs to happen to carry out this process
- [ ] Write it into the team compass

What do @yuvipanda @consideRatio and @GeorgianaElena think about this? And do you have any suggestions for how this work could be organized?

**Comment by consideRatio** [comment]
> - what are the general development ideas 2i2c is working on?
> - where can I observe this development and pitch in?
> - what needs to be done to accomplish these goals?

@yuvipanda made [this roadmap for a Canvas integration](https://hackmd.io/X1WPcV5NQ6CUFFIX8lZ-ig?edit) that i liked a lot! It contains concrete completion criterias for various parts as well as good down to earth motivations for the feature.

Perhaps this level of detail is useful both for developers and anyone else curious about the efforts. I'm not feeling confident on what forum make sense to publish roadmaps in (GitHub issues / discussions, jupyter-book, hackmd, etc), but I really appreciate the level of communication in this feature roadmap! Graspable and concrete without going into too much detail and keeping it short.

> - A single development repository where we keep track of issues for development and where it is happening (similar to our leads/ repository).
> - A single organization-wide GitHub Project board that contains development-focused issues that are spread out across many repositories

Not sure, I'm open for both ideas. Hmmm, if you use a project wide org board you can both can have issue at any location in the org right? Perhaps it can detect all issues and/or discussions with a certain label? Hmmm...

**Comment by choldgraf** [comment]
I am fine having "development to-dos and roadmaps" in several spaces, though if we do this we need to have a single space that is the "source of truth" for anyone who wants to answer the question "what are 2i2c team-members interested in working on, and where are they working on it"?

For example, I did not know that this "Canvas integration roadmap" existed because I suspect it has been mentioned in an issue somewhere that I was not following :-)

**Comment by yuvipanda** [comment]
Can you help me understand how this would be different than the tech team updates?

**Comment by yuvipanda** [comment]
> For example, I did not know that this "Canvas integration roadmap" existed because I suspect it has been mentioned in an issue somewhere that I was not following :-)

Nah, it was only mentioned in two slack channels and one microsoft teams chat :D But the next step was to follow the suggestion on the [OAuthenticator repo](https://github.com/jupyterhub/oauthenticator/pull/406) - create a new repo, push code into it, and maybe iterate on this publicly as a ROADMAP after advertising in community spaces (discourse, twitter, slack pings, gitter). I'd then probably put that into the tech update hackmd (I'm getting better at updating it!). Would be helpful for me to see what points of this could be changed to be more useful, while still being lightweight.

**Comment by choldgraf** [comment]
I am gonna close this one, because I think we are tracking it in #182 and #229
