### ISSUE TITLE
Fix broken links, and make future linkcheck's smooth

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/team-compass#283]
### Description

We have several broken links in our 2i2c.org website as managed in the https://github.com/2i2c-org/2i2c-org.github.io repository.

### Value / benefit

-

### Implementation details

This website isn't built using sphinx, but Hugo it seems, so there needs to be some other tool to handle this than the typical sphinx linkcheck as can be examplified from https://github.com/jupyterhub/the-littlest-jupyterhub/blob/main/docs/Makefile.

There are likely options.

### Tasks to complete

- [x] Fix the currently known broken links
  - http://2i2c.org/about/ has the following two known broken links
    - [x] "See our values for more information" : http://2i2c.org/values
      Should go to: https://2i2c.org/about/#values
    - [x] "See our services page for more information": http://2i2c.org/services
      Should go to http://2i2c.org/service/
    - [x] Support button, top right.
      Should go to https://2i2c.freshdesk.com/
- [x] Scan for other broken links and fix them also
  https://github.com/2i2c-org/2i2c-org.github.io/pull/82
- [ ] Implement linkcheck automation to trigger on PRs to the repo

**Comment by choldgraf** [comment]
I think we might be able to use this: https://github.com/Munter/netlify-plugin-checklinks ?

**Comment by sgibson91** [comment]
I build my personal website using Hugo and check links in CI like this: https://github.com/sgibson91/sgibson91.github.io/blob/e55f011e27273fc93c2952c9ff35a351da871b8a/.github/workflows/ci.yml#L57-L61

**Comment by choldgraf** [comment]
one thing we could do is just build the site with actions, even though it's also being built by Hugo, just to confirm that the links work OK

**Comment by consideRatio** [comment]
@choldgraf @sgibson91 could you confirm this is where we want to redirect with regards to support and values?
- Support: https://2i2c.freshdesk.com/
- Values: https://2i2c.org/about/#values

**Comment by choldgraf** [comment]
@consideRatio - values ✔️ support ✔️ 

the other missing link he mentioned was about *services*, and that should direct here: http://2i2c.org/service/

**Comment by consideRatio** [comment]
I'm leaving the linkcheck automation to be assigned as part of the next sprint.

**Comment by choldgraf** [comment]
I believe this is now resolved with https://github.com/2i2c-org/2i2c-org.github.io/pull/84
