### ISSUE TITLE
Archive 2i2c-org/upstream-activity/ and `upstream/`

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#285]
### Description

Should we archive https://github.com/2i2c-org/upstream-activity? It seems to be an unused duplicate of https://github.com/2i2c-org/upstream

### Value / benefit

- Less confusion about where we're tracking upstream contributions

### Tasks to complete

- [x] Make a decision to archive the repo or not
- [x] Move the `upstream-activity` repository to @choldgraf's account
- [x] Wait a week to migrate the `upstream/` repository so that people have a chance to move issues into backlogs
- [x] Archive the `upstream/` repository

**Comment by yuvipanda** [comment]
I didn't know the repo existed!

**Comment by choldgraf** [comment]
Ah that was my bad! I had created this repo as a testing ground for building a little auto-updating dashboard about our activity in upstream organizations. I didn't do it in upstream because I didn't wanna add noise there, but maybe I actually made more noise by doing it in a new repo?

**Comment by sgibson91** [comment]
@choldgraf Maybe? I was just a little bit confused about it when I searched for `upstream` and found `upstream-activity` as well. We may also ask what role `upstream` is playing now since we can add issues from outside the org to our sprint board (a feature the repo predates). We definitely need a method to collate upstream work for reporting/updating the community, for sure.

**Comment by choldgraf** [comment]
agreed - my feeling is that, because we can easily add upstream issues/PRs/etc to our project board, we could use the board to track this progress, rather than have duplicated issues that just happen to live in the 2i2c-org organization.

Presumably, GitHub Projects will also open up an API that we can hit, to do things like generate lists of issues that were closed and such. So I wonder if we could do something like:

- Use the Deliverables Backlog board to track upstream issues we want to tackle
- Archive the `2i2c-org/upstream` repository (or repurpose it to serve the dashboards I mentioned above, but don't use it for issues)
- Once a quarter, generate a list of closed issues that aren't under the `2i2c-org/` organization, to track the upstream issues we've worked on.

**Comment by sgibson91** [comment]
Yeah, there's a beta API already via the graphql endpoint https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects

**Comment by damianavila** [comment]
So, I guess we should remove/archive https://github.com/2i2c-org/upstream-activity now and, eventually do the same with the upstream one?

**Comment by choldgraf** [comment]
I want to play around with the upstream activity repository a bit more (to see if we can get some nice dashboards set up). So I'll move that repository to my personal account and we can decide if/when to bring it back into 2i2c spaces once there's something more concrete.

For the `upstream/` repository, I suggest we do the following:

- Stop opening issues there, and instead just add upstream issues to our backlog (and then sprint board)
- Give team members 1 week to transfer those issues to the backlog
- After a week, close the repository

That way people that have issues they really wanna keep track of can move it to a project (I suspect that this is actually relatively few issues).

**Comment by choldgraf** [comment]
this is now done! `upstream/` has been archived
