### ISSUE TITLE
Create a 2i2c sustainability team

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#300]
### Description

Right now there are several issues related to sustainability that are largely being spearheaded by Chris. Because he is also working on many other parts of 2i2c (see https://github.com/2i2c-org/meta/issues/256 among other conversations), there are likely sub-optimal decisions being made and balls being dropped. Moreover, Chris prefers working with teams of people rather than alone, and believes this leads to better decisions and outcomes in general.

## Suggested solution

I suggest we form a "sustainability team" within 2i2c. This is a team of people dedicated with overseeing 2i2c's strategy and execution of efforts to sustain and grow the organization. It includes topics like the following:

- Creating business strategy around 2i2c services
- Interfacing with the engineering team to guide the creation of this strategy
- Overseeing the execution of this strategy
- Developing new leads and collaboration opportunities for 2i2c
- Overseeing the sales process and touchpoints with CS&S (either doing the work directly, or delegating as necessary)
- Communicating sustainability-related efforts with the Steering Council or external partners.

## Who is on this team?

Anybody on the @2i2c-org/steering-council or @2i2c-org/tech-team is welcome to join this team. Being on this team means committing to attending most of the Sustainability Team meetings, and potentially working on items that are related to sustainability.

## Who leads this team?

Initially, I propose that this team is co-led by @colliand and @choldgraf.

## How does this team operate?

At its onset, this team meets once a week for a half hour, in order to triage and discuss major sustainability-related efforts and coordinate work. Over time this may change (particularly after the roll-out of the alpha service).

## Long term vision for this team

If 2i2c grows its services and team enough, this team would have a dedicated lead paid via 2i2c's funds as a "Director of sustainability" or a similar title. It might also morph into a slightly different focus (and potentially name) depending on our experiences in this run-through.

### Value / benefit

The goal of creating a team dedicated to this is so share knowledge and responsibility among several team members, as well as providing an explicit opportunity for more voices to be part of the "sustainability" conversation with 2i2c. This kind of work is important enough to 2i2c that it warrants dedicated thinking, and having a dedicated team to will help ensure that this happens. It is also potentially a nice pre-cursor to a persistent group that can work on these kinds of "businessy" things.

Another benefit is that this may be an opportunity to show leadership and innovation in the non-profit space. There aren't that many organizations that are governed and organized as a non-profit, but that also do things like "sales" and "customer service". This might be an opportunity for 2i2c to show leadership in how a values- and mission-driven organization can nonetheless achieve sustainability through a service model.

### Tasks to complete

- [ ] No objections to forming this team
- [ ] 2i2c members who are interested in joining this team ping in this issue
- [ ] Have our first team meeting and figure out what our work and communication cadence looks like
- [ ] Document this team in our team compass and website

**Comment by choldgraf** [comment]
# First questions

- Does anybody object to forming this team, or think it should be scoped / described differently?
- Is anybody in @2i2c-org/steering-council or @2i2c-org/tech-team interested in joining this team? Feel free to just say so in comments :-)

**Comment by yuvipanda** [comment]
While I won't be able to join, I'm excited to see this be formed!

**Comment by rabernat** [comment]
This sounds like a great idea! I would be interested in joining the team in the new year if you think I would be a good fit. (I can't take on any more this semester). I think I can bring an important perspective to the conversation as one of our guinea pigs for using sponsored-research funds (NSF, Moore) to pay 2i2c.

**Comment by choldgraf** [comment]
@rabernat I would highly value your contribution on this team, and would be thrilled for you to join :-)

Perhaps the next step then is to have an inaugural meeting of the sustainability team (even if it is just me and @colliand for now!) to figure out the right path forward.

**Comment by damianavila** [comment]
I would like to be part of these conversations/tasks and be able to help the team on this topic.
In addition, I think having one representative from the eng team would add some different perspectives.

**Comment by choldgraf** [comment]
Hey all - I had a conversation with @damianavila about this today and I'd like to propose two modifications to the issue here:

1. **Nominate @colliand as the team lead**. Jim has an interest in helping 2i2c improve its story and build a strong foundation for sustainability. I think he would be a great person to lead the strategy and team efforts here. I think it'll also be easier for us to coordinate if we have a point person to help guide the team.
2. **Create a designated representative from the engineering team on this team**. @damianavila brought up a good point that it is important to have cross-talk and sharing of information between more "sustainability/sales" groups and engineering groups, so that you have more shared context, know what is possible, etc. We should ensure that there's always somebody that can represent the perspective of the engineering team on the sustainability team (and probably vice versa?)
3. **Nominate @damianavila to be the representative of the engineering team**. In addition I believe @damianavila is interested in serving in this role on the team. If people agree with the engineering representative I described above, I think he'd be a good fit for this role.

**Comment by damianavila** [comment]
Thanks for the great summary about what we discussed, @choldgraf!

**Comment by colliand** [comment]
Thanks @choldgraf for bringing us together. I created a draft charter for the Sustainability Team. I welcome feedback and improvements. The Sustainability Team will vote to approve the Charter at our first meeting (to be scheduled).

# 2i2c Sustainability Team Charter


We convene a team to focus on ensuring the **sustainability** of 2i2c. 

2i2c will be sustainable when the organization generates enough revenue to cover all operational costs. 

2i2c aspires to generate revenue exceeding all operational costs so that the excess can be reinvested into a vibrant open source interactive computing ecosystem.

> The term _sustainability_ as used in the characterization of this team is not directly related to the Sustainable Development Goals identified by the United Nations. The larger 2i2c mission may address the SDGs.

 

### Purpose

The Sustainability Team (ST) develops strategies, and oversees and executes actions to sustain and grow the organization.



### Composition

ST members are drawn from the Steering Council, employees of 2i2c, and colleagues form CS&S. The Chair of the Team will liaise the Steering Council. A Member of the Team will liaise with the Engineering Team. A Member of the Team will liaise with CS&S.

### Responsibilities




ST's responsibilities include:

1. Develop a robust business around 2i2c's products and services
2. Implement an effective sales operation
3. Continuously improve the business in alignment with 2i2c's mission and values and within the 2i2c + CS&S relationship

### Meetings

1. ST will meet regularly (at least once per month) and as required.
2. Meeting minutes will be shared-by-default with Steering Council.

**Comment by colliand** [comment]
I wrote some notes aimed at describing a launch plan for the Sustainability Team. The notes are available [here on HackMD](https://hackmd.io/_RO3tCHoTrCdQGVRr9RRgg?view). An immediate need is to integrate sales + engineering to ensure that 2i2c will effectively deliver hubs we sell. I look forward to working with @damianavila and others on the engineering team to achieve that integration.

I will follow up soon with a request to find a time when we can meet. I understand that @rabernat will not be able to join us until early in 2022.

## 2021-11-29 ST Launch Plan

**Initial Membership**

+ @colliand (ST Lead)
+ @choldgraf (CS&S Liaison)
+ @damianavila (Engineering Liaison)
+ @rabernat (joining January 2022)

**Narrowing of focus:** 2i2c has ambitious long-term plans. Some of this vision is outlined in [these notes following a startup pitch format](https://hackmd.io/H7SCZ2DUSA-GU_mvTO6Zug?view). Our immediate focus is a more narrow near-term building block: validate 2i2c's capacity to sell managed JupyterHub service. To achieve that outcome, ST will need to develop some shared understanding of business ideas, adapt those to the alpha, and implement some systems to sell and deliver managed JupyterHub service. 

**Immediate Goals**

1. establish business around alpha service
2. design and implement **effective sales process** around alpha service
3. design and implement **effective service delivery process** around alpha service
4. prove 2i2c can achieve product-market fit with managed JupyterHub service

### Alpha service business


**Time interval** 

+ [2021-11-15, 2022-06-30]

**Offerings**

Two documents ([2i2c Alpha Service Offerings](https://docs.google.com/document/d/1FNiDyKNDoe_TgU2WxuNZ5CayYD56tlNJpImQsAIGOmg/edit), [Rationale for hub offerings and management fees](https://docs.google.com/document/d/1yEaSjIBkjZYmQDpzxyYuevxbG9unU9bfM-47vx96C44/edit#heading=h.5so35rkzpbpo)) describe and provide justifications for a collection of managed JupyterHub services with pricing:

| Type     | Shared Cluster | Dedicated Cluster |
| -------- | -------- | -------- |
| Education    | $1000/month    |   $1500/month |
| Research |  $1500/month | $2250/month | 
| Partnership | custom | custom |



#### Sales process

> Some background with useful ontology: [sales process](https://blog.close.com/how-to-build-a-sales-process-that-gets-results/); [sales operation](https://blog.close.com/sales-operations/); [sales cycle](https://blog.hubspot.com/sales/sales-cycle);  [lead → prospect → opportunity](https://blog.hubspot.com/sales/criteria-to-upgrade-a-lead-to-an-opportunity-and-theyre-not-what-you-think), [sales process engineering](https://en.wikipedia.org/wiki/Sales_process_engineering). A proviso: 95% of the writing on business, startups, sales, ... boils down to the author realizing that the scientific method works. 

2i2c has already sold managed JupyterHub service. This milestone was achieved with a combination of luck, manual effort, and latent trust available through prior interactions. Through the alpha, 2i2c aims to transition through manual, luck-based, existing-connections-based, word-of-mouth, unscalable sales toward a robust scalable data-informed business. 


##### Sales stages

Lead → Prospect → Opportunity → Close → Delivery → Expansion → Referral

+ Lead
    + an unqualified contact that might lead to a sale
    + inbound: person fills out a form
    + outbound: person responds to contact generated by 2i2c
    + qualify: lead → prospect
+ Prospect
    + prospect critera
        + persona potentially aligned with 2i2c mission
        + persona and usage scenario potentially aligned with alpha
        + BANT
            + budget
            + authority
            + needs
            + timeline
    + qualify: prospect → opportunity
+ Opportunity
    + understand prospect's organization/community
    + confirm prospect's needs met with alpha service offering
    + address obstacles to close
        + information security
        + privacy
        + demo
        + cost
+ Close
    + confirm sale following [defined process with CS&S](https://github.com/2i2c-org/team-compass/issues/262#issuecomment-971141123)
        + An email acknowledgement of the service tier that they want. We can send them the 2-pager, ask them to tell us which they want, and this is enough. We need to cc fsp@codeforsociety.org on the email so that they can keep track of this. This is the START email.
        + 2i2c Engineering team launches service. (See Delivery)
        + Engineering notifies 2i2c sales person when service is available.
        + 2i2c sales person prompts customer for email certifying the establishment of service.
        + An email acknowledgement once the services have been provided. For example, at the end of the month we can send them an email that has template language like "This email is to confirm that services XYZ have been provided as planned". And they respond with "yes I agree". This is the DELIVERED email.
    + CS&S invoices customer for setup fee with cc: partnerships@2i2c.org
    + CS&S collects setup payment
+ Delivery
    + 2i2c Engineering team + customer establishes service.
        + shared or dedicated cluster? If dedicated, share cloud billing and access details
        + SSO integration
        + Specify software environment
        + Specify support process
    + CS&S issues recurring monthly invoices for service.
    + If dedicated, 2i2c informs CS&S and customer of montly cloud costs.
    + CS&S issues invoice for monthly cloud costs. 
+ Expansion
    + 2i2c customer success team supports expansion toward Partnership tier
+ Referral
    + 2i2c customer success team seeks endorsement and referrals from customer to generate new business

##### Service delivery process


The following flow chart shows the process. It's rather complicated!

`

```mermaid
flowchart TD
    A((START email)) --> B{Set up service};
    B --> C[Dedicated];
    B --> D[Shared];
    C ---> E[Customer's cloud]
    C ---> F[2i2c's cloud]
    E ---> Q{Set up cluster}
    F ---> Q
    Q ---> R{Set up hub}
    D ---> R
    D --> G[Cloud cost]
    F --> G
    G ---> P[\Cloud Invoice/]
    R ---> H{Set up SSO}
    H ---> I{Set up SW Env}
    I --> J[Service Available]
    J --> K((DELIVERED email))
    K --> L[\Setup Invoice/]
    L --> M[\Monthly Invoice/]
    P --> M
    M ---> N[Expand]
    N ---> O[Referral]
```


<img width="384" alt="Screen Shot 2021-11-29 at 9 44 33 AM" src="https://user-images.githubusercontent.com/1879041/143917315-80f09fb6-2879-44b0-bd84-40ac93f7c353.png">

We need to work together to streamline the engineering steps required to establish service for a customer. 

we need to work with CS&S on the back office functions to build an effective business.
