### ISSUE TITLE
Support Steward: Sarah Gibson

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#317]
This issue transitions a support steward role to a new team member!
We transition support steward roles every two weeks.
The support steward rotates alphabetically through the 2i2c Engineering Team. Here's a [list of team members for support steward rotation](https://team-compass.2i2c.org/en/latest/about/team.html#open-infrastructure-team).

### Support steward

- Incoming Support Steward: @sgibson91 
- Outgoing Support Steward: Nobody! This is the first time we've done this on a 2-person team

### Useful info

- [Support Team membership issue](https://github.com/2i2c-org/team-compass/issues/294)
- [Support Team process](https://team-compass.2i2c.org/en/latest/projects/managed-hubs/support.html)
- [FreshDesk dashboard](https://2i2c.freshdesk.com/a/)
- [Open support issues and PRs](https://github.com/search?q=org%3A2i2c-org+label%3Asupport+is%3Aopen)

### Tasks to transition the support steward!

- [x] New support steward is named
- [ ] New support steward has discussed open support issues with outgoing support steward
- [x] New support team member is added [to the Support Team issue](https://github.com/2i2c-org/team-compass/issues/294)

**Comment by choldgraf** [comment]
I believe that normally we would assign the outgoing and incoming support steward to do a quick context-share with one another, but in this case I've just added @GeorgianaElena as the support steward who is continuing on, since there is no outgoing support steward!

**Comment by choldgraf** [comment]
Hey all - just want to ping on this one, have @sgibson91 and @GeorgianaElena shared context enough that they feel comfortable closing this issue?

**Comment by sgibson91** [comment]
We haven't discussed anything, but similarly nothing new has come in probably due to the holidays

**Comment by choldgraf** [comment]
In that case maybe you're fine closing the issue? Either you or @GeorgianaElena should feel free to close this whenever you think enough context has been shared! (including if there is no context to share haha)

**Comment by sgibson91** [comment]
I'm happy to close this. @GeorgianaElena please reopen if you feel differently!
