### ISSUE TITLE
Submit Abstract to present at UKRI Cloud WG Workshop

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#329]
### Description

The [UKRI Cloud Working Group](https://cloud.ac.uk/cloud-for-research-innovation/) holds a semi-regular [workshop](https://cloud.ac.uk/workshops/) that showcases the advancement and application of cloud technologies in the research sector.

The [call for the 2022 workshop is now open](https://cloud.ac.uk/2021/12/02/ukri-cloud-workshop-2022-call-for-participation/) and there are a few proposed (but not required) themes. One theme where I think 2i2c is in-scope is copied below.

> **Cloud Pilots and User Experiences**
>
> We would like to hear from operators and users about their experiences of running scientific workloads in private and public cloud environments. How does this compare with traditional HTC and HPC facilities? Have you found any advantages and/or disadvantages that we should know about? Do you use any abstraction layers to make them more usable?

There are also a few phrases in this second theme were I think we could discuss our deployment infrastructure and advocate for cloud agnosticity, open source tooling, and our Right to Replicate statement. (emphasis added to illustrate my point)

> **Hybrid Cloud**
>
> We are looking for examples of deployments which bridge the gap between on-premise infrastructure and public cloud, or **between cloud providers**. This could include; efforts to make **workloads portable between clouds**, creating cloud services or cloud access to enhance the current solution offered, or **technologies to support migration** and bursting, for example. In addition, topics covering data movement/migration and data collaboration/sharing have been of a particular interest to our community in the past and would fit within this theme.

### Value / benefit

- Advertises 2i2c as an org to the UK audience
- Champions 2i2c's values
- Centres @sgibson91 as a leader in cloud infrastructure for research in the UK

### Implementation details

- **Location:** The Crick Institute, London, UK
- **Date:** March 29th 2022
- **Deadline for abstract submission:** 17th January 2022
- **Link to submission form:** https://forms.gle/u7XEPpB79o2Y4rM27
- **Successful abstracts notified by:** 31st January 2022

### Tasks to complete

- [ ] Agree that @sgibson91 should submit an abstract
- [ ] Decide on a "Call to Action" for the abstract/talk
  - Is it "Come and buy 2i2c's services!", "Implement 2i2c's R2R in your own org!", something else?
- [ ] Write the abstract
- [ ] Submit it!

**Comment by sgibson91** [comment]
I've created a google doc to draft the abstract here: https://docs.google.com/document/d/1gFkT0eAlRwYs4aGIthvqOSQEjtfd2o8mByk5bZHjVak/edit?usp=sharing

**Comment by sgibson91** [comment]
I am going to see if this conference changes their opinion on not supporting remote speakers given the omicron surge. If they don't, I will close this and not submit anything.

**Comment by sgibson91** [comment]
I have not seen any update from this conference so I'm going to close this issue and not submit anything
