### ISSUE TITLE
Team Meeting: February

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#359]
This is a planning issue for our next team meeting! See below for information about the meeting and next steps.

### Information

_Information about when and where the meeting will take place_

- **Date:** 2021-02-01
- **Time:** 7:30AM US/Pacific time (or [**your timezone**](https://arewemeetingyet.com/Los%20Angeles/2021-02-01/07:30/2i2c%20Team%20Meeting#eyJ1cmwiOiJodHRwczovL2hhY2ttZC5pby9ZNVNCTXhWN1I2Q01xemVUWGdtNWtBIn0=))
- [**Video conference link**](https://zoom.2i2c.org)
- [**HackMD for meeting**](https://hackmd.io/Y5SBMxV7R6CMqzeTXgm5kA)
- [**Calendar for future meetings**](https://calendar.google.com/calendar/embed?src=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com&ctz=America%2FLos_Angeles)
- [**Calendar for Team Roles**](https://calendar.google.com/calendar/embed?src=c_nq8hl7qsm484g1p7mfkm29jpo8%40group.calendar.google.com&ctz=America%2FLos_Angeles)

# Follow up issues

_Links to follow up issues below_

- ...

### Tasks for the facilitator

_Steps to take to have the meeting._

- [ ] Agenda items added to the meeting
- [ ] Have the meeting
- [ ] Open up any follow-up issues or discussions and link above
- [ ] Cut notes out of HackMD and add to the Team Compass
- [ ] Team facilitator is handed off.

### Team roles

_List the current and next meeting facilitator using the list from our team roles calendar (see link above)_

- Facilitator for this month: {{ NAME }}
- Facilitator for next month: {{ NAME }}

**Comment by choldgraf** [comment]
This meeting is on the first day of the month, so our github action hasn't triggered yet for it! So we'll likely have duplicate issues for this when the action triggers, but I wanted to open this for now to track the updates.

**Comment by choldgraf** [comment]
### Call for agenda items + proposal for a shorter meeting

Two quick extra things:

- I've got one item on there to discuss our next hire with you all, but I suspect we'll have a decent amount of time remaining to discuss other things. If anybody would like to bring up a topic for discussion, please add it to the agenda!
- We need to move the steering council monthly meeting, as it overlaps by about 20 minutes with this meeting. In the meantime, I **propose that we shorten this meeting by 20 minutes this time**, since we don't have many agenda items anyway.
