### ISSUE TITLE
[blog] Cloud cost considerations for single-VM vs. Kubernetes

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#366]
### Summary / idea for post

This post will be for individuals who are thinking about cloud costs and the differences between running a single VM vs. a scalable cluster like Kubernetes.

Many organizations are not sure how to anticipate cloud costs, how costs scale with usage, and how their infrastructure decisions have a major impact on this. The goal of this post is to help them understand these considerations, and decide for themselves what the right path forward would be.

**Quick outline**

- Explain what contributes the most to cloud costs in general
- How does this break down in a JupyterHub-like scenario? What are the biggest bottlenecks?
- Simple case: use a single VM and TLJH - what will determine your costs?
- Show a usage curve (e.g. over one month) along with the machines you need to pay for over time
- Scalable case: how does Kubernetes change this equation? -> pay for smaller machines and more / fewer of them.
- Show the same usage curve, but now with another curve that more closely matches your usage, showing scalability
- Note about human operational needs / skills and how it differs
- Summarize a few major considerations to take

Here's a basic plot of the visualization I have in mind:

![image](https://user-images.githubusercontent.com/1839645/152589046-4a90cc34-dbe7-4ec0-98fa-000b6551dba7.png)

### Tasks and updates

- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)
