### ISSUE TITLE
[blog] 2022 - Q1 highlights

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#405]
### Summary / idea for post

We just wrapped up the first quarter of 2022, and I'd like to write up a short blog post that celebrates some of our accomplishments during that time!

To start, I wanted to brainstorm a few major highlights that 2i2c has accomplished. These are things like improvements to technology, open source contributions, communities we've served, experiments we've run, team and process improvements, etc.

I'm going to turn this into a little blog post + Tweet thread on Monday, with the goal of spending no more than 30 minutes on the whole thing :-) I don't want this to be a big chore or we won't do it regularly!

### Things we should celebrate

Below I'll start with a few ideas that come to the top of my head, but if anybody has ideas I welcome suggestions in the comments below! I'll split it into 4 main categories:

**Engineering developments**
- Finished our cluster and hub deployment infrastructure for each major cloud provider: https://github.com/2i2c-org/infrastructure/issues/627, https://github.com/2i2c-org/infrastructure/pull/1130,
- CILogon implementation and partnership: https://github.com/2i2c-org/infrastructure/pull/1089
- Major improvements to our CI/CD system:
  - Standardization, validation, automation, parallelization, and quality-of-life features for our SRE team
- Finished migrating all hubs to use the repo2docker action

[All the PRs we've merged in Q1](https://github.com/pulls?q=is%3Apr+merged%3A%3E2022-01-01+org%3A2i2c-org+archived%3Afalse+sort%3Aupdated-desc+)
[Closed issues in Q1](https://github.com/issues?page=4&q=is%3Aissue+closed%3A%3E2022-01-01+org%3A2i2c-org+sort%3Aupdated-desc)

**New communities served and what we've learned**

- UT Austin -> databases
- Toronto move to our infrastructure -> scale and complexity
- ANU hub -> prototyping CILogon
- uwhackweeks -> events process improvements / improving our AWS experience (e.g. ICESAT2 hackweek: https://twitter.com/scotty_h_q/status/1508557909751320577)
- LEAP Pangeo -> invoicing pass-through for cloud
- CarbonPlan -> set up GPUs + Azure experience

**Organizational improvements**

- New role designed: Product and Community Lead
- New role designed: Project Manager
- Many process improvements to our operations and support feedback loop
- First iterations on our CS&S invoicing and contracting process

**Open source / upstream contributions**

- Z2JH 2.0 prep-work
- PyData theme refactoring
- Sphinx Book Theme major update
- Binder sustainability efforts

### Tasks and updates

- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)
