### ISSUE TITLE
[blog] Quarter 2 update

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#452]
### Summary / idea for post

We just finished Quarter 2 of 2022! This is a short community update post to give others an idea of what we have been up to, major updates or accomplishments, and what we have learned.

### Major updates to cover

_We'll fill this in as ideas come in about things to cover_

### Tasks and updates

- [ ] Collect ideas for things to mention
- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)

**Comment by choldgraf** [comment]
### Please provide ideas to include above

Can folks on the @2i2c-org/tech-team as well as @2i2c-org/partnerships-and-community-guidance provide any high-level ideas for topics that you'd like to cover? This can be anything from technical improvements, to team and process improvements, to lessons we've learned, to highlights about impact that we've had.

**Comment by colliand** [comment]
The experience with the Eddy Symposium could be part of a blog post. Some observations on that event:

+ 2i2c responded quickly to the opportunity and deployed a hub in a little more than a week.
+ 2i2c initially deployed the hub with a Pangeo-style software environment and then improved and switched over to an image designed by and for heliophysics research.
+ 2i2c Co-Founder @fperez described living "la vida nube" in a talk at the start of the workshop. In response to requests from workshop participants, Fernando gave a demo on how to use the hub and an introduction to git.
+ 2i2c Co-Founder @colliand gave a talk on [governing the science commons](https://hackmd.io/@colliand/BJ4ZgZwdq#/). The idea that "intellectual generosity" should be the guiding virtue for open science resonated throughout the workshop.
+ The hub and collaborative guidance led to productive afternoon hackathon sessions that continue today. 

Another theme emerged over the week: 2i2c delivered a platform for collaborative computing that went beyond expectation, even among those familiar with the Jupyter ecoysystem. Some features that provoked oohs and aahs:
+ Launch a linux desktop in the browser
+ Authenticate to GitHub using tokens by executing a small notebook
+ The `shared` drive as a method to deploy data and content across the entire workshop

The Eddy Symposium demonstrated that 2i2c has capacity that goes beyond the delivery of technical resources for data-intensive research. 2i2c's capacity to demonstrate the **ways technology can be used for collaborative learning and research** is incredibly valuable. The lessons learned from this experience will inform improvements to 2i2c's approach to catalyzing effective communities following the launch of their hubs.

**Comment by damianavila** [comment]
A list of the most *remarkable* (my subjective interpretation) things we have done from Apr to Jun (data collected from our backlog and sprint/cycle boards from iteration 8 to iteration 13):

### Iteration 8

* https://github.com/2i2c-org/docs/pull/132
* https://github.com/2i2c-org/infrastructure/issues/586
* https://github.com/2i2c-org/docs/issues/135
* https://github.com/2i2c-org/infrastructure/issues/1146
* https://github.com/2i2c-org/infrastructure/issues/1216
* https://github.com/2i2c-org/infrastructure/issues/1173
* https://github.com/2i2c-org/infrastructure/issues/1237
* https://github.com/2i2c-org/infrastructure/issues/1168
* 

### Iteration 9

* https://github.com/2i2c-org/infrastructure/issues/1224
* https://github.com/2i2c-org/infrastructure/issues/1248
* https://github.com/2i2c-org/utoronto-image/issues/6
* https://github.com/2i2c-org/infrastructure/issues/967
* https://github.com/2i2c-org/infrastructure/pull/1249

### Iteration 10

* https://github.com/2i2c-org/infrastructure/issues/1252
* https://github.com/2i2c-org/infrastructure/issues/1220
* https://github.com/2i2c-org/infrastructure/pull/1314
* https://github.com/2i2c-org/infrastructure/pull/1322

### Iteration 11

* https://github.com/2i2c-org/leads/issues/56
* https://github.com/2i2c-org/infrastructure/issues/1329
* https://github.com/2i2c-org/team-compass/pull/427
* https://github.com/2i2c-org/docs/pull/144

### Iteration 12

* https://github.com/2i2c-org/meta/issues/256
* https://github.com/2i2c-org/infrastructure/issues/1338
* https://github.com/2i2c-org/infrastructure/issues/1309
* https://github.com/2i2c-org/docs/pull/143

### Iteration 13
* https://github.com/2i2c-org/infrastructure/issues/1437
* https://github.com/2i2c-org/infrastructure/issues/1154
  * https://github.com/2i2c-org/team-compass/pull/422
* https://github.com/2i2c-org/infrastructure/issues/1068
* https://github.com/2i2c-org/infrastructure/issues/1280
* https://github.com/2i2c-org/infrastructure/issues/1381
* https://github.com/2i2c-org/infrastructure/issues/1279
* https://github.com/2i2c-org/infrastructure/pull/1398
* https://github.com/2i2c-org/infrastructure/pull/1494
* https://github.com/2i2c-org/infrastructure/pull/1497

There are also some other issues such as https://github.com/2i2c-org/team-compass/issues/415 (and related https://github.com/2i2c-org/team-roles-geekbot-sweep/pull/43) which is essentially done but waiting to be deployed.
I guess we can talk about them after they are actually archived (next quarter). Another example would be the changes we have introduced from the PM perspective, it maybe makes sense to talk about them in the next quarter when we have a more complete picture.

Hopefully, this is helpful for you, @choldgraf!

**Comment by choldgraf** [comment]
Hey all - I dropped the ball on this one. I tried to quickly write down the content for a blog post, but found it difficult to pull out a couple high-level things from the list of merged PRs etc above. I'm going to close this issue because I don't think I have the time to write this blog post.

Here's a quick post-mortem on this issue in the hopes that it can help improve our team practices for this kind of thing in the future:

**Synthesizing high-level impact from low-level actions is hard**. I found it hard to define our high-level impact simply by parsing dozens of merged PRs and closed issues. It creates a lot of extra work to figure out the patterns there, and then to reverse-engineer our major accomplishments by looking at those patterns. Moreover, because my visibility is pretty high-level at 2i2c, I lack a lot of the context for each item that was completed so it's extra work to figure out the big picture.

There are two things I think we can do to more deliberately plan and communicate our actions:

1. **Define our 3-4 most important goals ahead of time**. I think we need to be more intentional about our goals for each quarter _ahead of time_. When we try to answer "what did we do this quarter?", the top 3-4 "big picture" items should already be there, and our goal should be to cross-reference our actual work against our intentions at the start. (maybe this happens more granularly than every quarter...but we need some kind of "planning cycle")
2. **Ask domain areas to define their own impact**. The people overseeing the work in various parts of 2i2c are the best ones to understand the impact that our actions were meant to have. In future iterations, we should have a (quarterly?) report in from engineering, community, product, and partnerships to define their own major impact items in one or two short paragraphs.

If others have suggestions, I would love to hear them. For now I'll close this and refer to the above points for future
