### ISSUE TITLE
[blog] Eddy symposium recap

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#467]
### Summary / idea for post

Recently, @colliand and @fperez joined the Eddy symposium where they had some nice experiences helping a community do better work via managed infrastructure that 2i2c provided. We should write up our experiences with this and share with others!

@colliand has put together a draft, so we can iterate from that one!

### Tasks and updates

- [x] Post draft: https://hackmd.io/L7XmF8XIQA29hDDmq2JaoQ?view
- [x] Blog location: 2i2c blog
- [x] Publish to blog
- [x] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)

**Comment by colliand** [comment]
This [pull request](https://github.com/2i2c-org/2i2c-org.github.io/pull/103) has a draft post. After the PR is approved this issue can be closed.

**Comment by damianavila** [comment]
https://github.com/2i2c-org/2i2c-org.github.io/pull/103 was merged, so let's close this one now.
Thanks, @colliand!

**Comment by damianavila** [comment]
Early close... blog post is live here: https://2i2c.org/blog/2022/eddy-symposium-report/
But there is some amplification to do yet...

**Comment by choldgraf** [comment]
@colliand if you don't have the cycles to post about this on twitter etc, I am happy to do so, just let me know! I just wanted you to have a shot at sharing the message if you wanted to

**Comment by damianavila** [comment]
@colliand tweeted 2 hrs ago: https://twitter.com/colliand/status/1547952717263384577?s=20&t=0F4IGNW8Cw_QGNA5qdS0nQ.
