### ISSUE TITLE
[blog] Three open questions for our service

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#473]
### Summary / idea for post

In some recent brainstorms with @malvikasharan @aldenc @harisood and @Arielle-Bennett, we came up with a few major questions to explore and answer as a part of improving our collaborative service model. This post will describe these questions briefly and note why we think they are both important and complex to answer.

This is meant to be a quick share-out from this meeting so that we are transparent about what we're thinking about, and in case others find it interesting or want to participate.

### Tasks and updates

- [ ] Finish https://github.com/2i2c-org/team-compass/issues/452 first
- [ ] Post draft: https://github.com/2i2c-org/2i2c-org.github.io/pull/104
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)

**Comment by choldgraf** [comment]
I'm going to close this one because I don't think I have the time to finish it, and need to prioritize other 2i2c stuff over writing this blog post. We really need to find a more time-efficient manner to get blog posts out there :-/
