### ISSUE TITLE
[blog] CZI Open Science grant

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#497]
### Summary / idea for post

We recently wrote a grant for a CZI Open Science invited proposal. See this issue for context:

- https://github.com/2i2c-org/leads/issues/78

Now that we've submitted the grant, we should publish a public version of the narrative so that others can read and potentially benefit from it. I've gotten an OK from the others on the grant that they're OK with this and have put the grant in this Zenodo entry:

- https://zenodo.org/record/7025288

We should write a quick outline about the narrative, and share it on social media.

### Tasks and updates

- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)
