### ISSUE TITLE
[blog] CZI ECB announcement

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#589]
### Summary / idea for post

We've been awarded the CZI grant for running a hub service for communities in South America and Africa. We already described it and shared a link to the grant, but should share a blog post telling the world that we got it!

### Tasks and updates

- [ ] Post draft: https://docs.google.com/document/d/1DWvblhGD_xv9GdhwOYlmUijQaMpghQvDYZXd0kvZ1Fo/edit?usp=sharing
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)

**Comment by choldgraf** [comment]
### Blog post draft is here

[Here's a draft to iterate on](https://docs.google.com/document/d/1DWvblhGD_xv9GdhwOYlmUijQaMpghQvDYZXd0kvZ1Fo/edit?usp=sharing)

**Comment by choldgraf** [comment]
### Need a two-sentence quote and a high-res image

I heard from Carly at CZI that they'd like a two-sentence quote and a high-res image to share. Will try to think on this today.

**Comment by choldgraf** [comment]
This is now posted here: https://2i2c.org/blog/2022/czi-global-communities-announcement/
