### ISSUE TITLE
[blog] 2i2c CILogon integration

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/team-compass#621]
### Summary / idea for post

**One-sentence description**

A summary of how CILogon is used at 2i2c, how the integration works and celebrate the partnership.

**Quick outline**

- the number and type of hubs at 2i2c that use CILogon
- the 2i2c cilogon infrastructure
- how the cilogon API allowed for automating various manual tasks
- upstream oauthenticator improvements?
- how cilogon's promptly supported 2i2c to quickly rotate client secret
- celebrate the parnership

### Tasks and updates

- [x] Post draft:  https://github.com/2i2c-org/2i2c-org.github.io/pull/148 (originally at  https://hackmd.io/@georgianaelena/rkkNYuzpi)
- [x] Blog location:  https://2i2c.org/blog/
- [x] Publish to blog
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv (optional)

**Comment by GeorgianaElena** [comment]
Update: draft of the blog post is at https://hackmd.io/@georgianaelena/rkkNYuzpi. Feedback much appreciated

**Comment by jbasney** [comment]
Thanks for drafting this post. It looks great! I made a few small edits in the draft.

**Comment by GeorgianaElena** [comment]
Thanks a lot @jbasney!

**Comment by GeorgianaElena** [comment]
Blog post available at https://2i2c.org/blog/2023/cilogon-integration.

Can someone with access to the 2i2c social accounts take responsibility for the last 2 points in the todo list (top comment), please? 
cc @2i2c-org/engineering @2i2c-org/team-leads

**Comment by damianavila** [comment]
I can take care of the tweet and the Linkedin post, @GeorgianaElena.
I self-assigned the issue for that.
Btw, I do not think we need to send it to 2i2c listserv.

**Comment by damianavila** [comment]
It seems I can't access Twitter for now but I could post it on LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7039259723304476673

**Comment by damianavila** [comment]
Now also tweeted from the 2i2c account: https://twitter.com/2i2c_org/status/1634191873593028608.
Closing here!
