### ISSUE TITLE
Clarify how to set up a local environment to work on our Sphinx documentation

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#637]
In https://github.com/2i2c-org/team-compass/pull/636 we got feedback from @colliand that our instructions for installing the environment to build our documentation are not clear enough. It is important that all of our team members are able to improve our documentation fluidly and without too much energy barrier, so we should improve our documentation for getting set up with Sphinx, given that this is a practice across all of our repositories.

### Tasks

- [ ] Define a central source of truth for "getting set up with a Sphinx environment"
- [ ] Make sure that the practice of building documentation is roughly the same across all of our repositories
- [ ] Remove redundant information and link back to the source of truth described above
- [ ] Ask @colliand to give it a run-through and see if this is clearer

**Comment by sgibson91** [comment]
If @colliand could provide the error messages he saw as well, that would be super helpful too!
