### ISSUE TITLE
Blog post: NASA TOPS-T grant

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#717]
We've received a grant from the NASA TOPS-T funding call. We should write a short blog post to tell others in the community about this. 

### Goals of the post

- Let us explain the "why" of this grant in our own words, and why we're excited about it
- Share with our external (and internal) stakeholders about this accomplishment for transparency

### Guidelines

- Not too long, maybe 300 words or so.
- Cross-reference grant material and other announcements

### Tasks

```[tasklist]
- [ ] Write a **short and rough** draft of ideas
- [ ] Give a runthrough and provide suggestions / edits
- [ ] Refine and then post
```

**Comment by choldgraf** [comment]
@jmunroe and I had a quick conversation about this last week, and agreed that to start he'd give a quick pass at describing his vision for the project and how it fits in with 2i2c's mission, and I'd take a pass at editing etc afterward. I've put that up in the todo list above.

@jmunroe can you try to get that very short draft done in the next few days, or will this need to wait until after the CZI meeting?

**Comment by choldgraf** [comment]
@jmunroe please let me know about any progress you've made on this. If you haven't started yet, let me know your capacity to work on it. If you don't have capacity then let's just forget it and cross-link to the NASA/CS&S blog post in our newsletter.

**Comment by choldgraf** [comment]
### This blog post will happen later

I spoke with @jmunroe and he mentioned that he's planning to use the blog post to bring in attention for a future role we'll hire on this + the CZI grant. So this will come out much later than right now. We don't need to block a newsletter on this post coming out.
