### ISSUE TITLE
[blog] CZI report

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#824]
### Summary / idea for post

We've posted our three year CZI report at the following link:

2i2c.org/report-czi-2021

We should write a short blog post about it.

### Tasks and updates

- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Post on social media ([Twitter](https://twitter.com/2i2c_org), [Mastodon](https://hachyderm.io/@2i2c_org), and [LinkedIn](https://www.linkedin.com/company/2i2c-org/))
- [ ] Send to 2i2c listserv (optional, generally this is for major updates)
