### ISSUE TITLE
[blog] Cloud billing guide

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#825]
### Summary / idea for post

@yuvipanda has written up a lot of useful information in our cloud billing guide:

https://infrastructure.2i2c.org/topic/billing/

We should put together a short blog post that highlights it and points people there.

### Tasks and updates

- [ ] Post draft: {LINK} 
- [ ] Blog location: {LINK} 
- [ ] Publish to blog
- [ ] Post on social media ([Twitter](https://twitter.com/2i2c_org), [Mastodon](https://hachyderm.io/@2i2c_org), and [LinkedIn](https://www.linkedin.com/company/2i2c-org/))
- [ ] Send to 2i2c listserv (optional, generally this is for major updates)
