### ISSUE TITLE
Define recurring dates and format for the first initiatives and operations board meetings

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#827]
We'd like to start running retrospectives and initiatives planning meetings on a regular basis. We also need to generalize the Partnerships board meetings to be Operations board meetings instead.

We need to answer a few questions to get running:

- choose a time/date and format for these meetings
- choose their format
- decide the roles and responsibilities for them
- kick it off with a first meeting

#### Iteration zero

- Monday, April 8th: initiatives retro, 9h30am California time

#### Iteration one

- Tuesday, April 9th: Initiatives planning, 9h30am California time
- Thursday, April 11th: Operations iteration planning, 8h00am California time

2 weeks pass...

- Monday, April 22rd: Initiatives retrospective
- Tuesday, April 23rd: Operations retrospective, 8h00am California time

#### Iteration two

- Tuesday, April 23: Initiatives planning
- Thursday, April 25: Operations iteration planning

2 weeks pass...

- Monday, May 7: Initiatives retrospective
- Tuesday, May 8: Operations retrospective

```[tasklist]
### Tasks
- [x] Initiatives: Agree on planning and refinement meeting time
- [x] Initiatives: Agree on planning and refinement meeting facilitator
- [x] Initiatives: Agree on retrospective meeting time
- [x] Initiatives: Agree on retrospective facilitator
- [x] Operations: Agree on iteration planning meeting time
- [x] Operations: Agree on iteration planning meeting facilitator
- [x] Operations: Agree on retrospectives meeting time
- [x] Operations: Agree on retrospectives meeting facilitator
```

**Comment by choldgraf** [comment]
I'm adding @haroldcampbell and @aprilmj to this issue because I think you've both already been discussion about holding these meetings. Is that right? Could you identify a time to take a first iteration? I don't think we need things to be perfect but we just need to "pick a time" to start trying out the process for these efforts.

**Comment by aprilmj** [comment]
We have a "solutions forum" (which we should update to call "initiatives") pair of calls - retro and planning - on April 8 and 9. 

We described initiatives retro/planning as wrapping around the Operations sprint planning. How would you all feel about squeezing a very very tiny Ops sprint in next week? Too much too soon?

**Comment by aprilmj** [comment]
@jmunroe suggested that we could take over the Partnerships time slot - any objections to that? 

(from [`initiatives slack`](https://2i2c.slack.com/archives/C06G5FAAT63/p1711974546320559)

**Comment by choldgraf** [comment]
There are 4 meetings we're talking about here:

- Initiatives
	1. Iteration planning
	2. Retrospective
- Operations
	1. Iteration planning
	2. Retrospective

And the Partnerships-specific iteration/retrospective meetings are going away. Assuming that engineering meetings times will not change.

I wasn't sure which meeting you were talking about here, so I looked at the dates and I think I figured out the proposal that you're making. I've updated the top comment with that proposal (specifically, the "operations iteration planning" time slot, as the initiatives time slots would remain the same, I think).

So a few requests:

1. Let me know if the info in the top comment looks incorrect.
2. For me that time often works, and sometimes will not due to childcare constraints. That's OK with me.
3. Can somebody propose a time for the operations retrospective?

**Comment by aprilmj** [comment]
> ## Footnotes
> 
>     1. For the future: it is helpful if you include all the context needed to understand a proposal in the github issue, since that's the source of truth for our discussions. E.g., in this case instead of just saying "can we take over the partnerships time slot?" it would have made it easier to include the specific time/day of week of the slot, and which meeting we were talking about, rather than asking people to dig through a Slack conversation to understand the context. [↩](#user-content-fnref-1-97643617a9e73cb4e199f46e83538dc9)

Thanks for the feedback! That made a lot of sense to me.

**Comment by aprilmj** [comment]
@choldgraf The updated top comment looks correct to me. 

I think the next logical time for the Operations retrospective would be Tuesday, April 23rd, given the iteration planning will be on Thursday, April 25 - does 8am PDT work? 

I'm basing the day and time off the current Partnerships retro pattern. That call's at 8am PDT on Tuesdays, with the most recent one being today (apologies if I've got this wrong @jmunroe).

**Comment by jmunroe** [comment]
The cycle for the operations retrospective and planning look right to me.

**Comment by choldgraf** [comment]
There are two things that we need to converge on this one:

### Meeting times and initial next steps

I've updated the top comment with what I _think_ are our next actions here. It assumes that **starting next week we begin a new iteration**. Here's that that means next:

- Monday "ends" the current iteration with an initiatives retrospective.
- Tuesday "begins" iteration 1 with an initiatives refinement meeting.
- Thursday continues iteration 1 with operations iteration planning.
- Two weeks pass...
- And then we finish iteration 1 with an operations + initiatives retrospective.

Does that look correct? 

### Who will facilitate these meetings and their format?

@haroldcampbell has facilitated these meetings previously, does he intend on doing so moving forward as well? If not, who or what process will facilitate the meetings?

**Comment by jmunroe** [comment]
For the Operations retrospective, I would like to continue to use the same process to facilitate that we have been practicing in the Partnerships and Engineering retrospectives:

Last partnerships retro:  https://easyretro.io/publicboard/BcByiOpA7kO5XVozuqxcvTsalLT2/aa9e2b75-1d2e-4ddc-b10b-744f8b768458
Last engineering retro: https://easyretro.io/publicboard/Cz5xV2lbTRh8TWqagNrvaFJ44oH3/f518e91a-42cc-4090-b1c4-84e585efaa65

I assume it makes sense to use this same process for the Initiatives retrospective as well.

**Comment by jmunroe** [comment]
To close out this issue, we have the following two retrospectives now scheduled:

- Initiatives Retro, April 22, 9:30am California time, @jmunroe agreed to facilitate 
- Operations Retro, April 23, 8:00am California time, @aprilmj agreed to facilitate

Calendar invites have been sent out so closing this issue.
