### ISSUE TITLE
[EPIC] Understanding and observing the types of unplanned work engineering does

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#901]
### Context

In order to reduce unplanned work in the team, we first need to understand what unplanned work the team is performing and how it arises. To achieve this understanding we need to define what is unplanned work and create a process to surface it. This epic tracks those tasks.

The need for this epic was raised during a retrospective meeting.

### Task list

```[tasklist]
- [ ] https://github.com/2i2c-org/team-compass/issues/904
- [ ] https://github.com/2i2c-org/team-compass/issues/903
- [ ] https://github.com/2i2c-org/team-compass/issues/902
```

### Definition of Done

- Documentation for the above items exists in the Engineering section of the Team Compass

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by Gman0909** [comment]
I believe we now have a working system for tracking and managing unplanned work - would you agree this issue can now be archived?
