### ISSUE TITLE
Setup "Brown Bag" sessions for technical discussions to facilitate knowledge sharing

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#908]
### Context

To reduce the impact of internal, project-based siloes in engineering (e.g. "Person A did Project X, so only they have the knowledge"), we would like to introduce a "Brown Bag" event to hold technical discussions which will facilitate knowledge sharing and help weaken siloes.

I, Sarah, want to make this as open and and flexible as possible so that i) people feel like there's always _something_ they could present, even if they haven't just nicely wrapped up a Super-Cool project; and ii) it doesn't feel like a bro-y, "that's what the engineers do" kind of space.

### Tasks

```[tasklist]
- [x] Make some decisions on how to format and run the "Brown Bag" sessions based on prior art
- [x] Setup a place to store information about upcoming and past events
- [x] Document the culture and expectations around this event, e.g. in the team compass
- [ ] https://github.com/2i2c-org/team-compass/issues/911
- [x] Advertise and find first speaker
```

### Definition of Done

- A place to store info on upcoming and past sessions exists
- The culture and expectations around the event are documented
- A recurring schedule for the sessions is set
- 2i2c staff are aware of the event and it's context
- There is a speaker organised for the first session

**Comment by sgibson91** [comment]
### Proposal

_Some rough first thoughts:_

- Meeting format:
  - 45min video call
- Meeting frequency:
  - Every 2 weeks? Maybe even monthly if we think about how few people we have to rotate through. (Can also always be changed later)
- Who can present?
  - Expectation that engineers will present
  - Anyone from org welcome to present
- Presentation format:
  - To be decided by presenter! Everything from traditional slide decks to hands on walkthroughs and beyond should be permitted! Let's make this safe to try and _fun_!
- Who can attend?
  - Expectation for engineers to attend
  - Anyone from org welcome to attend
- Topic to be presented on, _in order of preference_:
  - Completed or ongoing technical project work within 2i2c (AirTable and stuff from Biz Dev counts!)
  - Completed or ongoing technical work from upstream partners of 2i2c
  - Hobby technical projects. If you had to deep dive into some framework while realising your dream to remotely brew coffee from your office so that it was ready in the time it takes you to walk to the kitchen, let's hear about that learning journey!
  - Also encourage topic _requests_, "can someone talk about X?"
  - Practising external talks to gather feedback
- How do we track who is presenting when?
  - TBD - probably a sign-up sheet of some description. Google sheets? GitHub wiki?
- How do we encourage people to_actually sign up_?
  - TBD
- How/where do we store the resources of the talk (e.g. slide deck links) for future reference?
  - Could be the same place as the schedule

**Comment by sgibson91** [comment]
I updated the name to "Brown Bag" because this will not be happening at lunch time for everyone 😂

**Comment by consideRatio** [comment]
Me and Sarah have a meet scheduled on monday about this, I look to help work this with a kickstart in that meet.

**Comment by sgibson91** [comment]
Erik and I met, he thumbs up the plan and we agreed that I will take this forward as it turns out the Turing's wiki is _not_ open like I thought, I'm just still an external collaborator from when I worked there 😅

**Comment by sgibson91** [comment]
I am breaking off the "setting a schedule" part of this task as it's own issue while we wait for the flurry of new meetings following the re-org to settle.
